### ISSUE TITLE
Hue bulp devicesNumber 99999981 is missing

### ISSUE THREAD

**Issue by asblass** [homecineplexx/ioBroker.homepilot20#12]
Hi Chris,

thank you for the awesome ioBroker adapter, works like a charm. I've found that the Philips Hue Whilte Lamp LWB010 is not recognized by the adapter. The deviceNumber is 99999981. Maybe you like to implement this type, too :-)

Best,
Andreas

**Comment by homecineplexx** [comment]
Hi
I will implement this, but i need some help of you

greets,
chris

**Comment by asblass** [comment]
Hi Chris,

sure, where can I help you.

Viele Grüße
Andreas

**Comment by homecineplexx** [comment]
can you copy the warn message from ioBroker log

**Comment by asblass** [comment]
Here they are:

homepilot20.0 | 2020-01-31 13:41:21.552 | warn | (394) Unknown Actuator deviceNumber=99999981
homepilot20.0 | 2020-01-31 13:41:21.551 | warn | (394) Unknown Actuator deviceNumber=99999981
homepilot20.0 | 2020-01-31 13:41:21.549 | warn | (394) Unknown Actuator deviceNumber=99999981
homepilot20.0 | 2020-01-31 13:41:21.549 | warn | (394) Unknown Actuator deviceNumber=99999981

**Comment by homecineplexx** [comment]
gefixt and you can find a new npm version 0.0.7
