### ISSUE TITLE
Heizkörperstellantrieb 8433

### ISSUE THREAD

**Issue by DangerDragon95** [homecineplexx/ioBroker.homepilot20#14]
Hallo,
ist es möglich den Batteriestatus des z-wave Heizkörperstellantrieb 8433 im iobroker anzuzeigen?
bei dem neueren Modell Heizkörperstellantrieb 9433 wird dieser korrekt im iobroker angezeigt.

Grüße
René

**Comment by homecineplexx** [comment]
Guten Morgen
also der Z-Wave liefert soweit ich weiß und mich erinnern kann keine Werte mit. Weder für die Batterie, noch für die IST-Temperatur.
Sollte ich mich täuschen, dann häng doch bitte hier den Output des REST Requests an.

Danke
Greets Chris

**Comment by DangerDragon95** [comment]
Hallo,
im Homepilot wird von beiden Modellen der Batteriestand angezeigt. bei dem neueren wird zusätzlich die IST-Temperatur angezeigt.
ich habe leider wenig Ahnung was du für einen Request brauchst. meinst du sowas?

{"val":12,"ack":true,"ts":1582042643377,"q":0,"from":"system.adapter.homepilot20.0","user":"system.user.admin","lc":1584261996452,"type":"state","common":{"name":"Heizung Wohnzimmer","desc":"batteryStatus stored in homepilot for device 10076","type":"number","role":"value","unit":"%","min":0,"read":true,"write":false},"native":{},"_id":"homepilot20.0.Actuator.10076-35003064.batteryStatus","acl":{"object":1636,"state":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"}}

der ist vom Objekt Temperatur des neuen Modells

Vielen Dank
René

**Comment by homecineplexx** [comment]
ja genau...du brauchst mir aber nichts vom neuen DuoFern Heizkörperstellantrieb schicken. Der funktioniert auch...den hab ich in Verwendung!!

**Comment by DangerDragon95** [comment]
Hier ein Request vom alten Thermostat
{"type":"channel","common":{"name":"Heizung Rene","role":"text"},"native":{},"from":"system.adapter.homepilot20.0","user":"system.user.admin","ts":1584717279715,"_id":"homepilot20.0.Actuator.10079-35002319","acl":{"object":1636,"owner":"system.user.admin","ownerGroup":"system.group.administrator"}}

Ich hoffe das hilft dir. ich weiss nicht von welchem objekt (Position devicenumber...) du was brauchst.

vilen dank
René

**Comment by homecineplexx** [comment]
nochmals, das Z-Wace Teil schickt keinen Batteriestatus mit, soweit ich mich noch erinnern kann
