### ISSUE TITLE
Installing as an Adapter in ioBroker

### ISSUE THREAD

**Issue by Bri-Gitte** [homecineplexx/ioBroker.homepilot20#15]
Hi,

i'm completely new to ioBroker and i would like to install your adapter to use my Rademacher homepilot. Is there a tutorial how to install it manually?

Thanks for your work!

**Comment by mjanker4247** [comment]
I had the same question and finally managed it with the following commands:
```
cd /opt/iobroker
iobroker stop
sudo -H -u iobroker npm install iobroker.homepilot20
iobroker upload homepilot20
iobroker start
iobroker add homepilot20 --host <hostname>
```
