### ISSUE TITLE
Cannot stop a moving window blind

### ISSUE THREAD

**Issue by mjanker4247** [homecineplexx/ioBroker.homepilot20#16]
**Describe the bug**  
If I tell Siri ("Hey Siri, stop window bling <room>") to stop a moving window blind it doesn't stop, but closing it.

**Versions:**  
 - Adapter version: 0.0.10
 - JS-Controller version: 3.1.6
 - Node version: 10.21.0
 - Operating system: Linux 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux on RaspberryPi 3

**Comment by homecineplexx** [comment]
but this is not part of my adapter. 
you can move and stop your blinds via my adapter. if some problems are on siri, please test this with siri!!
