### ISSUE TITLE
Adapter ist weder im Default noch im latest Repository enthalten

### ISSUE THREAD

**Issue by Bibo13** [homecineplexx/ioBroker.homepilot20#17]
Hallo,
war der Adapter nicht schon mal im Repo enthalten?
Im jetzigen Zustand wird nicht auf Updates hingewiesen ist das so gewollt?

Hello,
wasn't the adapter already included in the repo?
In the current state, updates are not indicated. Is that what you want?

**Comment by homecineplexx** [comment]
sorry, ich hatte noch nicht die zeit, dass ich mir das ansehe, wie es ins repo kommt.

mach ich bei zeiten. 
das ist eben der neue Homepilot ab einer neuen version
