### ISSUE TITLE
No reaction of the sensors

### ISSUE THREAD

**Issue by Siegmunder** [homecineplexx/ioBroker.homepilot20#18]
Hello, 
I'm using the last version of the homepilot20 - 0.9.
All my components that are registred on the Hompilot are displayd. That's ok.
But I have the "Umweltsensor (9475)" and three "Tür- und Fensterkontakt" (9431) and they are displayd but they shows no reaction.The attributes do not change.
I have the impression, that the showing attributes are dummy values. Is it so? Or it's a little bug?

Regards Siegmunder

**Comment by homecineplexx** [comment]
hello

the latest version is 0.0.11
and i use the same like you and it works! so please reload your browser and test it again!

**Comment by Siegmunder** [comment]
I looked in the log and there were two errors. The reason was that the password protection in the homepilot was stwiched off. The status dot in iobroker was green despite the error. Why? The adapater was stopped. 
But now it works.
