### ISSUE TITLE
Adjusting positions of lamellas

### ISSUE THREAD

**Issue by chrid88** [homecineplexx/ioBroker.homepilot20#20]
When trying to intigrate the lamella position by using the signal slatposition  it seems to read the right value from homepilot as it matches the actual position. But when i try to change the value e.g. via slider widget nothing happens to the lamella as it stays in his original position.
I hope you can fix this as i would really like to use this adapter
Here is a picture of one of my doufern basic.
Could it be that it has to do with slatposition being a text and not a levelblind?
[https://ibb.co/C8twLSX](url)

**Comment by homecineplexx** [comment]
i dont know where or how you wanna integrate a parameter called "slatposition".

but can you give me the range of the possible slatposition? 0-100 ??

**Comment by chrid88** [comment]
Hallo @homecineplexx 
der Einfachheit halber auf deutsch:
Kopier den Link in den Browser, ich hab wohl was verbockt bei der Hyperlink Funktion.
Die "slatposition" ist der Neigungswinkel der Raffstore-Lamellen und liegt zwischen 0 und 100%
Der Wert wird bereits (wie im Screenshot zu sehen) richtig aus dem Homepilot ausgelesen.
Er reagiert aber leider nicht auf eine Veränderung z.B. mittels Slider Widget.

**Comment by homecineplexx** [comment]
also ich kann dir das machen, wenn du mir schickst, welcher REST Request da abgesetzt wird für DuoFern-TrollBasis-5615 (das ist doch das Teil, das du hast oder??)

**Comment by chrid88** [comment]
Ja genau ist der 5615.
Das wäre natürlich Hammer, wenn du das einbauen würdest.
Wie kann ich den REST Request denn auslesen?

**Comment by homecineplexx** [comment]
naja du verwendest hoffentlich einen Browser und zwar am besten den CHROME.
du gehst mal mit dem Browser auf deinen HomePilot und dann klickst du auf eines der 5615.
klickts rechte Maustaste und dann im Menü der Maus auf Untersuchen, dann sollten die Developer-Tools des Browsers aufgehen.
Dort gehst du auf Network.
und dann änderst du die slatposition und dann sollte unten irgendwo stehen, was er abschickt (bissl schwer zu erklär)

**Comment by chrid88** [comment]
Ok, das hört sich schaffbar an ;)
Ich werds mir heute abend nach der Arbeit ansehen!

**Comment by homecineplexx** [comment]
ja bitte mach das...dann können wir das einbauen und du testest das mal

**Comment by chrid88** [comment]
Nachdem ich einen der Raffstore auf 99% Position gefahren habe, habe ich diesen Abschnitt gefunden:{"name":"CURR_SLAT_POS_CFG","value":"99","min_value":"0","max_value":"100","step_size":"1","read_only":false,"timestamp":1605634924}
Hilft dir das?

**Comment by homecineplexx** [comment]
ich werd da mal was basteln und dir bescheid geben!

**Comment by homecineplexx** [comment]
lieber chrid88

ich glaub nicht dass das der befehl ist, womit man das setzt. das ist eher die position. 
du mußt schauen, wenn du das network laufen läßt und du den slat-wert am Homepilot direkt änderst, müßtest du da einen REST Request sehen, mit dem Command

kannst du mir das raus finden?

**Comment by chrid88** [comment]
Hi,
ich werde nochmal schauen was da passiert.
Ich hab immer wieder das Network Log geleert und dann den Befehl ausgelöst.
Aber so richtig bin ich dann nicht schlau geworden.
Ich habe dann halt mal nach "99" gesucht und dachte ich würde so den Befehl finden, der diese Position übermittelt hat...
Scheint leider nicht erfolgreich gewesen zu sein

**Comment by chrid88** [comment]
{"name":"SET_SLAT_POS_CMD","min_value":"0","max_value":"100","step_size":"1","read_only":false,"timestamp":-1}},{"name":"GOTO_POS_SLAT_CMD","read_only":false,"timestamp":-1}},{"name":"DFLT_SLAT_POS_CFG","value":"1","min_value":"0","max_value":"100","step_size":"1","read_only":false,"timestamp":1605892851}

Diese drei Einträge sehen für mich noch vorstellbar aus.
Kann es sein, dass der letzte mein Treffer ist? Dieser Eintrag hat ja nen Timestamp...

**Comment by homecineplexx** [comment]
also ich werde eine 0.0.13 version bauen und hier das "GOTO_POS_SLAT_CMD" einbauen, denn das klingt mir am vernünftigsten. 
ich würde dich aber dann bitten, dass du es testest und mir ein Feedback gibst

**Comment by homecineplexx** [comment]
> {"name":"SET_SLAT_POS_CMD","min_value":"0","max_value":"100","step_size":"1","read_only":false,"timestamp":-1}},{"name":"GOTO_POS_SLAT_CMD","read_only":false,"timestamp":-1}},{"name":"DFLT_SLAT_POS_CFG","value":"1","min_value":"0","max_value":"100","step_size":"1","read_only":false,"timestamp":1605892851}
> 
> Diese drei Einträge sehen für mich noch vorstellbar aus.
> Kann es sein, dass der letzte mein Treffer ist? Dieser Eintrag hat ja nen Timestamp...
so, die Version 0.0.13 ist da, bitte teste das und gib mir ein feedback....danke

**Comment by funky4t** [comment]
DFLT steht sicherlich für Default und bildet die Standardlamellenposition ab, in welche der HP die Lamelle nach manueller Bedienung durch die App dreht. Ich würde auch Goto oder Set probieren.
LG Sven

**Comment by homecineplexx** [comment]
> DFLT steht sicherlich für Default und bildet die Standardlamellenposition ab, in welche der HP die Lamelle nach manueller Bedienung durch die App dreht. Ich würde auch Goto oder Set probieren.
> LG Sven


hi
wenn du so etwas daheim hast, könntest du schnell die 0.0.13 Version ausprobieren?

**Comment by homecineplexx** [comment]
funky4t hast du dieses Device daheim und könntest du die 0.0.13 ausprobieren?

**Comment by funky4t** [comment]
Leider hab ich die selbst nicht im Einsatz, alles auf Rollotron ohne Raffstores hier. Kenn die nur von diversen "Vorort-Einsätzen" im Handling vom HomePilot. Sonst hätte ich euch sofort unterstütz.👍🏼😃

**Comment by homecineplexx** [comment]
oh danke, das wäre ja sehr nett gewesen. was machst du beruflich, weil du von "VorOrt-Einsätzen" sprichst?

**Comment by chrid88** [comment]
super danke, wie bekomme ich denn die 0.13 jetzt genau eingespielt?
Ich habe versucht über eine neuinstallation zu gehen, er sagt zwar, dass er ein Paket geupdatet hat, aber am Ende bin ich immer noch bei version 0.11...

**Comment by homecineplexx** [comment]
an chrid88:

also du gehst auf Instanzen und deaktivierst mal den homepilot20.
dann gehst du unter Adapter auf die "Katze" und dort gibts einen Reiter namens "Beliebig". 
unter diesem Reiter gibts ein Eingabefeld "URL und Dateipfad" und dort kopierst du dann die URL vom Git-Repo https://github.com/homecineplexx/ioBroker.homepilot20 
rein

wenn die Installation fertig ist, sollte 0.0.14 dort stehen. dann kannst die Instanz wieder starten!

Viel Spaß

**Comment by chrid88** [comment]
ok Update hat geklappt.
leider bleiben die Lamellen noch stehen :( 
![image](https://user-images.githubusercontent.com/73813530/99905053-c2527100-2cce-11eb-9cbd-60db7742b170.png)
Das markierte Signal nutze ich für einen Slider.
Wenn ich diesen dann versuche in einer Demoview zu bewegen, passiert aber weiterhin nix.
Mit der Position des Raffstore (vermutlich der gleiche Befehl um ein Rollo zu fahren) funktioniert alles super.

Was mich irritiert ist, dass es sich bei der Slatposition um einen Text handelt. Bei der Position aber um level.blind.
Kann das ein Fehler sein?

**Comment by homecineplexx** [comment]
dh du hast die 0.0.14 Version?

dann würde ich dich bitten, nicht über ein Widget das zu steuern, sondern den Wert direkt da oben bei "slatposition" einzutragen!

ob da level.blind, oder hamtidamit steht, ist prinzipiell egal. wichtig ist nur, dass der Adapter merkt, dass du den Wert in den Objekten umgetragen hast und einen Befehl Richtung Homepilot schickt (und zwar den hoffenltich richtigen :-) ).

danke

**Comment by chrid88** [comment]
also wenn ich unter objects den pfad im Iobroker aufrufe, mir schreibrechte für das feld besorge und dann 0,2 oder 0.2 oder 20 eingebe passiert nix bzw. ich bekomme ein popup text der false sagt und es springt wieder auf die aktuelle position.
Ich werde nochmal den traffix durchforsten bzw. macht es sinn, dir ggf. mal das komplette log (also nicht nur den slatposition fitzel) zu schicken? ggf. übersehe ich ja was

**Comment by homecineplexx** [comment]
ich hab noch etwas geändert und eine 0.0.15 Version gebaut. versuch die doch mal bitte!
danke

**Comment by chrid88** [comment]
getestet, leider ohne Ergebnis.
Ich habe jetzt glaube ich einen Fehler bei mir gefunden.
Im Developer Tool habe ich immer die "Nachricht"  die der Device Nummer entspricht (z.B. "8") genommen und ausgelesen.
In Anlehnung an die Struktur im Adapter gibt es aber noch eine andere Nachricht mit Bezeichnung "devices?devtype=Actuator.
Hier finde ich dieses Statement:
{"response":"get_visible_devices","devices":[{"description":"Raffstore","deviceGroup":2,"did":1,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset6"},"messages":[],"name":"Wohnzimmer Ecke","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":2,"temperature":3,"time":2,"trigger":3,"warning":3,"wind":2},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":99,"slatposition":76},"visible":true,"deviceNumber":"36500172","uid":"4cb729_1","voiceControlledBy":"","origin":"HomePilot"}

Danach folgen die weiteren Geräte.
Ist hier evtl. der Fahrbefehl unter dem Stichwort Manuelbetrieb?

**Comment by homecineplexx** [comment]
nein nein, das ist nur der Momentanzustand aller.
ich bau jetzt etwas um und in 10 minuten solltest eine neue Version haben. ich glaub ich habs jetzt wirklich!!

**Comment by chrid88** [comment]
Ok schade.
Zum letzten Update: der Fehler war eigentlich der gleiche, nur das ich diesmal die write permission nicht extra einholen musste.

**Comment by homecineplexx** [comment]
so bitte jetzt auf die 0.0.16 updaten. jetzt gehts sicher. ich hab da oben bei den Befehlen glaub ich zuerst was überlesen!

**Comment by chrid88** [comment]
Läuft!!!
Der einzige Verbesserungspunkt wäre noch, dass du wie in der 15er version den wert direkt schreibbar machst. Ich musste jetzt erst wieder das schreiben "aktivieren".
Aber sonst sehr cool!!
Danke :)

**Comment by homecineplexx** [comment]
nein, das Objekt sollte schreibbar sein! da hats was bei dir!
mach entweder einen Browser reload, oder stop den Adapter und lösch das ganze device, dann wirds neu angelegt

**Comment by chrid88** [comment]
Alles klar, werd ich morgen testen und feedback geben! Aber wie gesagt erstmal danke

**Comment by homecineplexx** [comment]
super, dann schließ ich das hier nun ...viel spaß damit
