### ISSUE TITLE
Auto Manu Switching

### ISSUE THREAD

**Issue by funky4t** [homecineplexx/ioBroker.homepilot20#21]
Hi Chris,
Was ich letztens mal für IOBroker Integration meine Rollladengeräte gesucht habe: Den Datenpunkt für Auto/Manu Umschaltung. Irgendwie finde ich den nicht. Im HP und der App kann ich den per Switch ändern und das auch schon seit langer Zeit. Übersehe ich in den Datenpunkten des Adapters etwas? Die Geräte ließen sich so dann auch mit anderen Fenster/Türkontakten über IOBroker koppeln. Fenster Auf, Automatik aus. Nix Kritisches aber vielleicht eine sinnvolle Erweiterung, falls ich die nicht übersehen habe! 🙈 LG Sven

**Comment by homecineplexx** [comment]
hallo
Das hab ich damals extra nicht integriert, weil man diese Automatik meiner Meinung nach direkt im ioBroker abbilden kann und damit machts kaum mehr Sinn. Denn du willst ja vielleicht wissen was passiert. Und wenn du das nun im Homepilot läßt, bekommst du von dieser Automatik in der Zentrale nichts mehr mit, bzw du siehst zwar dass deine Rollläden etwas machen, aber du weißt nicht wer der Auslöser ist und warum das passiert. Aber ich kann das gern nach-implementieren wenn du das magst?!

**Comment by funky4t** [comment]
Hi Chris, du hast generell wohl recht sofern man den ioBroker als "leading system" betrachtet und z.B. die Beschattungsautomatik per Script im IO steuert. Ich stell mir nur vor, wenn du z.B. bei einer Sonnenautomatik ein einzelnes Fenster deaktivieren willst, müsste doch im globalen IO-Script für jedes Fenster ein Switch als Datenpunkt her, der z.B. sagt Fenster 3 von insgesamt 10 soll nun nicht fahren. Oder das gesamte Script würde global deaktiviert.
Würde jetzt dein IO Broker deine Anlage komplett steuern, könnte ich mit einem Datenpunkt AUTOMATIK "true","false" relativ einfach ein Fenster per Switch in den MANU-Mode setzen ohne in mein unter Umständen komplexes Script einzugreifen. Das Script würde ALLE Fenster ansteuern, der Homepilot gibt auch an Fenster 3 weiter, das "hört" den Befehl aber nicht.

Ich sehe das aber vielleicht auch, aufgrund mangelnder Programmierkenntnisse, eher aus der Anwendersicht. So kann ich über den ioBroker in die Automatik des Aktors total easy "durchgreifen" statt mir zu überlegen, wie ich das in den iobroker Code bekomme. Selbst damit hätte ich mit meinem Stand (im Blockly ;)) eine einfachere Falls Prüfung mit einem AUTO state. 
Also quasi falls Fenster3 Automatik = "true" mache Beschattung, else "mache nix". Sollte der Switch fälschlicherweise auf FALSE stehen, sollte das Fenster auch eher nicht mehr fahren statt zu fahren ohne dass du weißt warum. Also immer vorausgesetzt dass die Automatik ein geschalteter State und nicht ein Pushbutton ist, bei letzterem gebe ich dir komplett recht, dann sehe ich den Aktorstatus ohne Rückmeldung im IObroker nicht. Aber im HP ist das ja auch ein Schalter...

Ich gebe aber zu, dass ich meine Beschattung aktuell noch komplett über Homepilot fahre...funktioniert halt gut und in IObroker fuxe ich mich aktuell immer noch mit Sachen rein, die der HP nicht so gut oder garnicht kann... ;) Powermetering, Öltanks mit SR04 und Tasmota auslesen und Jarvis und so.... :) Ich bräuchte einfach mehr Zeit...oder weniger Schlaf... lol

Also wenn der Aufwand für dich überschaubar ist, könnt ich mir vorstellen, dass dieser State mir sowie aber auch einigen IOBroker Anfängern durchaus helfen könnte. Es reicht meines Erachtens auch, die "Globale" Automatik zu integrieren und auf die jeweiligen Splits in Sonnenaufgang, Sonnenuntergang und Zeit zu verzichten. Die nutzt meiner Erfahrung nach eh kaum jemand gezielt.

Grüße in die "Nachbarhauptstadt" aus Oberfranken,
Sven

**Comment by homecineplexx** [comment]
ich werd mich dem auch demnächst annehmen. 
das Problem ist nur, dass ich zuerst schauen muß, welche Devices alle diesen AutomatikModus haben und wie man dessen Wert ändert. 

sollte aber alles kein Problem sein (Zeitproblem eher)

**Comment by funky4t** [comment]
Moin,
Mach dir diesbezüglich bitte überhaupt keinen Stress, das ist für mich keinesfalls zeitkritisch. War eher etwas was mir auffiel und wo ich denke das wäre noch ne gute Erweiterung. Soweit läuft alles andere im Adapter ja perfekt! 😃

**Comment by homecineplexx** [comment]
also ich hab für die Devices, die ich habe, alle Auto-Funktionen eingabaut.
Sollten welche fehlen, bitte neue Issues aufmachen. 
Danke
