### ISSUE TITLE
Rademacher Bridge

### ISSUE THREAD

**Issue by deus82ex** [homecineplexx/ioBroker.homepilot20#22]
Hi,

is it possible to use the adapter with the bridge?

https://www.rademacher.de/shop/rollladen-sonnenschutz/fernbedienung/bridge

Regards
Mario

**Comment by homecineplexx** [comment]
yes, it works with the Bridge

**Comment by deus82ex** [comment]
Thanks for reply. Maybe you can help me. I added the IP in configuration, instance turns grren on start, but no device is shown. Do I have to add a port (if yes which port) or anything else? In the homepilot app and via alexa my device works fine.

**Comment by funky4t** [comment]
@deus82ex 
Port should not be needed. Did you try restart of instance/IOBroker/homepilot or bridge?

**Comment by deus82ex** [comment]
I restarted again, but all I see in my objects is this:

![image](https://user-images.githubusercontent.com/45871700/99527482-28708880-299d-11eb-8f12-b7fd2da03845.png)

**Comment by funky4t** [comment]
Homepilot not connected = true means bridge or pilot is not reachable for the adapter. Are you sure IP of Bridge/homepilot is properly set? Even without port it should be working... Did you use HomePilot.local or the direct IP? Use IP from your HomePilot App under Einstellungen-Geräteienstellungen-Netzwerk-LAN Then indicator should switch to false and devices should show up

**Comment by deus82ex** [comment]
Hab ich alles gemacht.

![image](https://user-images.githubusercontent.com/45871700/99536167-485a7900-29aa-11eb-8108-b90f2bdbf856.png)

unter devices zeigt es jetzt nur eine homepilot devices json an

![image](https://user-images.githubusercontent.com/45871700/99536348-85bf0680-29aa-11eb-9918-c724f6c5fd82.png)

**Comment by funky4t** [comment]
Ich fürchte du hast die "alte Version" vom HomePilot Adapter installiert. Die unterstütz nur Homepilots bis Firmware 4.x und sicher auch nicht die Bridge! Das Logo oben links im Adapter ist jedenfalls alt und nicht gleich zu dem wie bei mir!
Weißt du wie du den Adapter hier von GitHub installierst? Gibt bei den Adaptern "die Katze" oder direkt über URL hier von GitHub installieren! Ich tippe du hast den Adapter über IOBroker direkt installiert?!

**Comment by deus82ex** [comment]
Ja genau, danke für den Tipp. Teste ich nachher. 


Holen Sie sich Outlook für Android

**Comment by deus82ex** [comment]
Hat funktioniert danke.

Ich dachte über die direkte Installation erhalte ich immer die aktuelle Version?

**Comment by funky4t** [comment]
Das sogenannte repository kannst in IOBroker zwar umstellen, davon wird aber vielfach abgeraten, da sonst immer unklar ist, was die Mods und Forenspezies so supporten! Über den IOBroker bekommst du leider nur den alten Adapter, ich weiß nichtmal, ob der auch vom gleichen Entwickler stammt. So "verschließt" sich der IOBroker gegen Adapter im Betastatus usw. Ich hab meinen auch nicht umgestellt, bin zu sehr "User" ;) Der Adapter hier funzt soweit wird aber bis jetzt nicht als stable im IOBroker anerkannt.

Aber toll dass der Adaptet jetzt bei dir rennt! Mit der Bridge zusammen, so war es doch bei dir, also nicht HomePilot sondern Bridge? Für IOBroker auch völlig ausreichend... 😉

**Comment by deus82ex** [comment]
JA genau,

ich hab mir so ein Starterkit mit Bridge und einem Gurtwickler gekauft um das mal zu testen. IOBroker hab ich auch erst seit paar Tagen im Einsatz.

Soweit sehr zufrieden. Hab noch paar Gosund Steckdosen auf Tosmato und Homematic IP Thermostate und paar Yeelight.

 

Von: funky4t <notifications@github.com> 
Gesendet: Mittwoch, 18. November 2020 18:35
An: homecineplexx/ioBroker.homepilot20 <ioBroker.homepilot20@noreply.github.com>
Cc: Mario Oertel <mail@m-oertel.de>; Mention <mention@noreply.github.com>
Betreff: Re: [homecineplexx/ioBroker.homepilot20] Rademacher Bridge (#22)

 

Das sogenannte repository kannst in IOBroker zwar umstellen, davon wird aber vielfach abgeraten, da sonst immer unklar ist, was die Mods und Forenspezies so supporten! Über den IOBroker bekommst du leider nur den alten Adapter, ich weiß nichtmal, ob der auch vom gleichen Entwickler stammt. So "verschließt" sich der IOBroker gegen Adapter im Betastatus usw. Ich hab meinen auch nicht umgestellt, bin zu sehr "User" ;) Der Adapter hier funzt soweit wird aber bis jetzt nicht als stable im IOBroker anerkannt.

Aber toll dass der Adaptet jetzt bei dir rennt! Mit der Bridge zusammen, so war es doch bei dir, also nicht HomePilot sondern Bridge? Für IOBroker auch völlig ausreichend... 😉

**Comment by funky4t** [comment]
Na dann viel Spass beim testen mit iO und Bridge und den ersten Steps in iobroker. Empfehlung von meiner Seite, lass das iobroker repository grade zum Anfang auf "stable" dann sind deine installierten Adapter auch ausreichend getestet. Bei wenigen Ausnahmen dann halt auf "latest" umstellen oder benötigten Adapter wie hier aus git ziehen. 
Und Achtung, der ioBroker macht süchtig!!! :)

**Comment by homecineplexx** [comment]
nein ich bin nicht der selbe der den anderen/alten/ersten Homepilot Adapter entwickelt hat. sind auch ganz unterschiedliche Schnittstellen.

er ist deshalb nicht im Stable da ich noch keine Zeit hatte mich darum zu kümmern. Ausserdem rennt er ja gut ;-)

viel Spaß dabei

**Comment by deus82ex** [comment]
Das Log ist voll von folgenden Meldungen, lässt sich das unterbinden?

homepilot20.0 | 2020-11-19 19:50:50.254 | warn | (1736) Scenes -> Cannot connect to Homepilot: {"statusCode":501,"body":"Not implemented for Bridge!","headers":{"server":"nginx/1.17.1","date":"Thu, 19 Nov 2020 18:50:50 GMT","content-type":"text/htm

**Comment by homecineplexx** [comment]
Hallo
Könntest du mir bitte ein neues Ticket/Issue dafür aufmachen.
Danke

**Comment by Gucky28** [comment]
Hallo,

Ich bin neu hier und habe auch die Rolladen mit Gurtwicklern von Rademacher. Jetzt möchte Ich diese auch über IO Brocker laufen lassen nur leider geht das nicht.
Wenn Ich das Richtig verstanden habe gibt es aber einen Adapter hier auf GitHub.
Da Ich überhaupt keine Ahnung habe wie Ich den finde und wie Ich den installiere brauche Ich euere Hilfe am liebsten eine Anleitung geht das ???

Danke im voraus

**Comment by funky4t** [comment]
> Hallo,
> 
> Ich bin neu hier und habe auch die Rolladen mit Gurtwicklern von Rademacher. Jetzt möchte Ich diese auch über IO Brocker laufen lassen nur leider geht das nicht.
> Wenn Ich das Richtig verstanden habe gibt es aber einen Adapter hier auf GitHub.
> Da Ich überhaupt keine Ahnung habe wie Ich den finde und wie Ich den installiere brauche Ich euere Hilfe am liebsten eine Anleitung geht das ???
> 
> Danke im voraus

Hi Gucky,
ein paar mehr Details von dir bräuchten wir aber dann doch! 😂
Welche Wickler hast du denn von Rademacher? Sind die funkfähig, also die Varianten MIT DuoFern? Hast du einen Homepilot oder eine SmartBridge bereits im Einsatz, oder nur die Wickler?
Du schreibst: "Jetzt möchte Ich diese auch über IO Brocker laufen lassen nur leider geht das nicht." - Was genau geht denn nicht, was hast du bereist probiert, an welcher Stelle genau hakt es?

Weißt du, wie du den Adapter über Github in Iobroker installierst?
Wir helfen Die sehr gerne, aber ein paar mehr Infos wie, welcher Wickler, welches Gateway und welcher Kenntnisstand im ioBroker musst du uns schon geben, dann haben wir Lösungsansätze für dich zum prüfen... :)

Anleitung braucht es normal nicht, denn due installierst, den Adapter in Iobroker, fügst die IP deines Gateways hinzu und findest dann alle Geräte die am Homepilot/Bridge hängen auch im Iobroker.

Gib mal ein paar mehr Details, dann kriegen wir das auch zum Laufen! ;) LG Sven

**Comment by funky4t** [comment]
Hier der Weg, wie du den Adapter in Iobroker installierst, falls du da nicht weiter kommst:

Adapter -> auf Katze -> von GIT -> Beliebig wechseln -> URL reinkopieren: https://github.com/homecineplexx/ioBroker.homepilot20 

Dann auf "Installieren" und warten bis der Adapter auf iobroker installiert ist. Instanz erstellen, IP rein, fertig.

<img width="1440" alt="Bildschirmfoto 2021-05-16 um 21 00 52" src="https://user-images.githubusercontent.com/57875762/118409396-80592500-b68a-11eb-954f-79f1269c84e0.png">

**Comment by Gucky28** [comment]
Hallo Sven,

Also Ich habe die Rademacher Start2Smart Kit Smart Home Zentrale + 2x Funk-Gurtwickler RolloTron Basis DuoFern 1200 
mit der Bridge dazu. Alles ist installiert und lässt sich super mit der App und Alexa steuern.

Nun habe Ich aber eine VIS in IObroker und möchte die Gurtwickler auch von dort Steuern und gegeben falls später mit der Wetterstation von homematic IP und CCU3 Steuern. Das nur zur Info.

Wie Ich den Adapter installiere, weiß ich leider nicht so richtig über Github in den Iobroker.

Ich hoffe das hilft weiter :-)

Danke im voraus

**Comment by Gucky28** [comment]
Hallo nochmal :-)

Genau das habe Ich gebraucht den Link zu dem Adapter zur Installation.

Danke jetzt komme Ich erstmal weiter, wenn Ich später noch Fragen habe dann würde Ich mich gern noch mal melden dürfen.

Besten Dank und noch einen schönen Abend

**Comment by funky4t** [comment]
Hey Gucky,
das hilft, du hast erstmal funkfähige Rollotrons und die BRIDGE, also den abgespeckten Homepilot! ;)
Geh mal bitte den Weg wie oben im Screenshot gezeigt, du musst den Adapter wie dort beschrieben installieren, da der Adapter nicht im latest oder stable repository von iobroker ist. Darum den Link hier von Git unter "Beliebig" reinkopieren und installieren! ;)

Alles klar, dann halt ich hier mal eben an.... Wenn was ist, melden! :D Viel Erfolg! :)

**Comment by Gucky28** [comment]
Hallo,
erst noch mal Danke für die Hilfe damals.
Nun ist es wieder so weit Ich habe meinen Raspberry Pi3 getauscht zu einem Raspberry PI4.
Soweit so gut nun ist es so, dass Ich natürlich meinen Homepilot (Bridge) wieder über den Iobroker steuern möchte aber es funktioniert nicht.
Ich habe es genau wie oben neu installiert aber es kommt immer eine Warn Meldung im Log, Bild sende Ich mit und die Geräte werden nicht gezeigt, obwohl der Adapter grün ist.

Grüße Andreas

**Comment by funky4t** [comment]
Moinsen,
der Wechsel von RPi3 zu 4 sollte das Problemchen nicht verursachen!
Prüf mal bitte, ob deine Bridge mit der genannten IP noch erreichbar ist... ich tippe auf eine neue ip bei der bridge und dann kann der Adapter sie unter der alten IP nicht mehr finden. schau mal nach der Bridge in der Einstellungen des Adapters....
Parallel mal nach der IP der Bridge in der App schauen, sollte dann auch die 76 da stehen.

**Comment by homecineplexx** [comment]
hallo
wie schon funky4t geschrieben hat, bitte überprüfe ob du auf die IP 192.167.178.76:8000 kommst, wenn nicht, dann such bitte den fehler in deinem netzwerk!
lg chris

**Comment by Gucky28** [comment]
Das geht ohne Probleme komme locker auf die ip im Browser.

**Comment by funky4t** [comment]
Konfiguration im adapter mal gelöscht und neu angelegt?
Adapter mal gelöscht, neu installiert?
wüsste nicht, dass an Bridge oder Adapter ein Update stattgefunden hätte....

**Comment by Gucky28** [comment]
Ja mehrfach sogar

**Comment by funky4t** [comment]
Hast den 3er PI noch rumfliegen? Was sagt der im Adapter-Log? 
Ich kann da ehrlicherweis keine logische Erklärung für finden! Hast du an der Bridge was geändert? Hau doch der Bridge mal ne andere interne IP in den Kopf und ändere die neue dann im Adapter.... Passwort in der Bridge eingerichtet? Geht das überhaupt?!??!? 🙈 kannst du vom raspberry auf die Bridge nen Ping geben? Doofe Frage, Bridge mal neu gestartet, vlt. hängt da was? 🤣

**Comment by Gucky28** [comment]
Also Bridge mehrfach neugestartet. Adapter neu installiert.  Den alten Pi hab ich noch nur der Broker läuft leider komischer weiße nicht mehr schaue Morgen noch mal nach.

Dann melde ich mich wieder

Danke schonmal bis hier her 😀

**Comment by Gucky28** [comment]
Hallo,

Ich hatte keine Geduld und habe dann doch noch mal hier und da versucht was einzustellen am Adapter und Ich weiß ehrlich gesagt nicht wie oder was Ich gemacht habe es geht plötzlich wieder 

Danke an alle

**Comment by funky4t** [comment]
Naja gemacht haben WIR ja nix! 😜 Aber eigentlich blieb nur die Config des Adapters oder nen verwurstetes Netzwerk! 🤣

**Comment by Musiktoto** [comment]
Hallo!
Meine Smart2Smart Rademacher Bridge hat wohl über Nacht ein Update auf die Version 5.8.20 gemacht.
Seitdem kann ich meine Rolläden nicht mehr steuern.
Die installierte Version von homepilot20.0 ist 0.0.64.
Im Log von IOBroker steht folgendes:
**homepilot20.0 | 2024-11-14 12:39:12.478 | warn | Transmitter sensors -> Cannot connect to Homepilot: Error: getaddrinfo ENOTFOUND http**
Also der homepilot20.0 bekommt wohl keine Verbindung mehr zur Bridge!
Wenn ich die IP der Bridge im Browser öffnen, ist sie ohne Probleme erreichbar.

**Comment by funky4t** [comment]
Hi,
mein HP rennt nach wie vor sauber auf 5.8.20, ist aber eben ein HP und keine Bridge. 
Hat sich die Bridge eventuell eine neue IP bei dir gezogen, die du zwar öffnen kannst aber im Adapter noch nicht geändert hast? Wäre fast zu einfach, aber manchmal ist mir genau sowas selbst schon passiert.

**Comment by funky4t** [comment]
Und Häckchen bei "Bridge" ist auch gesetzt?

**Comment by homecineplexx** [comment]
Hallo
also mein Hp läuft auch ohne Probleme seit Jahren.
den Log den du mit schickst, ist nur ein WARNING, dass er die Transmitter sensors nicht mehr erreicht. 
wie oft kommt dieser Log? Welche Zeit hast du eingestellt im Adapter?
schick mal ein Foto mit von den Adapter Settings!

gibt mal `http://ip/v4/devices?devtype=Transmitter` ein und zeig den Response.

**Comment by homecineplexx** [comment]
> Hi, mein HP rennt nach wie vor sauber auf 5.8.20, ist aber eben ein HP und keine Bridge. Hat sich die Bridge eventuell eine neue IP bei dir gezogen, die du zwar öffnen kannst aber im Adapter noch nicht geändert hast? Wäre fast zu einfach, aber manchmal ist mir genau sowas selbst schon passiert.

Hallo
daher sollte man auch mit fixen IPs arbeiten. Machts einfacher

**Comment by Musiktoto** [comment]
Hallo Nocheinmal!
Ich kann Entwarnung geben!
Nach dem Update der Bridge, startet die sich ja selbst neu. Und da muss irgendwas schief gelaufen sein.
Ich hatte heute Mittag 2 Stunden des Fehler gesucht, warum die Steuerung über IOBroker nicht mehr funktioniert hat.
Als letzte Maßnahme habe ich nun mal die Bridge und den Router komplett vom Strom genommen.
Zusätzlich habe ich den Raspberry, auf dem der IOBroker läuft, neu gestartet.
Was soll ich sagen, nachdem alles wieder hochgefahren war, konnte ich im IOBroker unter Objekte / homepilot20 sehen, wie nach und nach die Aktoren wieder sichtbar wurden.
Waran das jetzt im Endeffekt gelegen hat, läßt sich leider nicht genau nachvollziehen!

**Comment by funky4t** [comment]
> > Hi, mein HP rennt nach wie vor sauber auf 5.8.20, ist aber eben ein HP und keine Bridge. Hat sich die Bridge eventuell eine neue IP bei dir gezogen, die du zwar öffnen kannst aber im Adapter noch nicht geändert hast? Wäre fast zu einfach, aber manchmal ist mir genau sowas selbst schon passiert.
> 
> Hallo daher sollte man auch mit fixen IPs arbeiten. Machts einfacher

solange man die fixen IPs nicht vergisst oder sie in unbekannten Netzen suchen muss sehr von Vorteil! ;)
