### ISSUE TITLE
Das Log ist voll von folgenden Meldungen, lässt sich das unterbinden?

### ISSUE THREAD

**Issue by funky4t** [homecineplexx/ioBroker.homepilot20#23]
Das Log ist voll von folgenden Meldungen, lässt sich das unterbinden?

homepilot20.0 | 2020-11-19 19:50:50.254 | warn | (1736) Scenes -> Cannot connect to Homepilot: {"statusCode":501,"body":"Not implemented for Bridge!","headers":{"server":"nginx/1.17.1","date":"Thu, 19 Nov 2020 18:50:50 GMT","content-type":"text/htm

__Originally posted by @deus82ex in https://github.com/homecineplexx/ioBroker.homepilot20/issues/22#issuecomment-730569538__

**Comment by homecineplexx** [comment]
super, danke

könntest du schauen, ob es sich da nur um "Scenes" handelt welche in den Logs ausgespuckt werden?

**Comment by funky4t** [comment]
Hi Chris,

Die Bridge unterstützt im Gegensatz zum HP weder Szenen noch Auslöser. Ich vermute dass der HomePilot Adapter hier nicht fündig wird und das Log mit Fehlern füllt.
Die Bridge kann ebenfalls keine Cams und keine Hue Bridge. 
Eventuell ne Abfrage am Start ob Bridge oder HP angebunden und bei Bridge diverse Abfrage nicht ausführen bzw. im IOBroker Log melden?

**Comment by homecineplexx** [comment]
Hallo
Danke für die Erklärung, dem bin ich mir bewußt!
Ich wollte eigentlich nur wissen, ob er sonst noch was (anderes) im Log schreibt. Dann könnte ich gleich anderes auch fixen

danke

**Comment by funky4t** [comment]
Hi,
Sorry deine Frage sah ich erst nach meiner Info, war also nich als Antwort drauf bezogen. Warten wir also auf die Logs vom Mario! 😃

**Comment by deus82ex** [comment]
Hallo Männer,


bei mir werden nur die Szenen angemeckert. 


Holen Sie sich Outlook für Android

**Comment by homecineplexx** [comment]
also ich bin schon dran an dem Thema und es schaut sehr gut aus. ich hoffe aus zeitlichen Gründen morgen Abend eine funktionierende Version für euch zu haben. :+1:

**Comment by homecineplexx** [comment]
also, die 0.0.12 Version ist online und sollte euer Problem beheben. 
viel Spaß beim Testen

**Comment by deus82ex** [comment]
Moin, ich hab das Update eingespielt, aber die Meldungen sind noch da:

![image](https://user-images.githubusercontent.com/45871700/99764865-3ab60800-2afe-11eb-89be-2932bd82a193.png)

homepilot20.0 | 2020-11-20 06:59:15.399 | warn | (9632) Scenes -> Cannot connect to Homepilot: {"statusCode":501,"body":"Not implemented for Bridge!","headers":{"server":"nginx/1.17.1","date":"Fri, 20 Nov 2020 05:59:16 GMT","content-type":"text/html
-- | -- | -- | --

**Comment by deus82ex** [comment]
Sry, hab grad gesehen, dass du eine Checkbox für die Bridge eingebaut hast. Wenn man die setzt, dann ist Ruhe im Log.

**Comment by homecineplexx** [comment]
ja das war ja auch der Sinn der Übung :-D

also damit funktioniert die Bridge und somit ist es genug hier in dem ISSUE
