### ISSUE TITLE
Auto Attributes for homepilot20.0.Actuator.1010000-16234511

### ISSUE THREAD

**Issue by funky4t** [homecineplexx/ioBroker.homepilot20#24]
also ich hab für die Devices, die ich habe, alle Auto-Funktionen eingabaut.
Sollten welche fehlen, bitte neue Issues aufmachen. 
Danke

_Originally posted by @homecineplexx in https://github.com/homecineplexx/ioBroker.homepilot20/issues/21#issuecomment-731655054_

Hi Chris,

also ich hab Auf und Unterputzwickler. Die Aufputz sind mit Auto/Manu Attributes vorhanden, super Danke für die Erweiterung!
Der 1800 Unterputz (homepilot20.0.Actuator.1010000-16234511) nicht. Für mich nicht zeitkritisch, aber bei den Beschattungsgeräten ist AUTO MANU Umschaltung meines Erachtens interessant. Ich kann deinen Programmieraufwand überhaupt nicht einschätzen, aber falls es dir hilft: Ich denke der DP "AUTO_MODE_CFG" wäre für die meisten schon ausreichend, da ich niemanden kenne, der gezielt einzelne Automatiken schaltet, wohl aber Situationen wo ein Nutzer mal ein Gerät KOMPLETT aus der Automatik nimmt. Also falls das deinen Aufwand der Integration mindert. Für mich jetzt auch nicht zeitkritisch, kannst du beim nächsten Update mal mit integrieren.

Rollotron Comfort 1800: homepilot20.0.Actuator.1010000-16234511 hat bei mir keinen "Attributes"-Ordner
Rollotron Standard 2510 (1400): homepilot20.0.Actuator.1010035-14234511 hat die Attributes

Gruß Sven

**Comment by funky4t** [comment]
ID 23602075 von den S-Line FUNKmotoren wäre auch noch so ein Kandidat für zukünftige Integration

**Comment by homecineplexx** [comment]
Kannst du mir für den Rollotron Comfort 1800  vielleicht ein Foto machen und Anhängen oder mir hier schreiben, welche Automatik-Modi der hat, denn wenn integrier ich alle.

und was genau ist dieser ID 23602075
ich integrier gern die Sachen, aber ich tu mir eben schwer bei Dingen die ich leider nicht selbst habe.
Da hat wäre immer eine Teil zum testen ganz gut

**Comment by homecineplexx** [comment]
> ID 23602075 von den S-Line FUNKmotoren wäre auch noch so ein Kandidat für zukünftige Integration

Kannst du mir für den Rollotron Comfort 1800 vielleicht ein Foto machen und Anhängen oder mir hier schreiben, welche Automatik-Modi der hat, denn wenn integrier ich alle.

und was genau ist dieser ID 23602075
ich integrier gern die Sachen, aber ich tu mir eben schwer bei Dingen die ich leider nicht selbst habe.
Da hat wäre immer eine Teil zum testen ganz gut

**Comment by funky4t** [comment]
Hi,
Hier mal nen Screenshot zu den Automatiken in der App beim Rollotron1800

![image](https://user-images.githubusercontent.com/57875762/100102242-9f0cfa80-2e63-11eb-89bf-c263817a80e6.png)

Der 1800er hat im Gerät noch eigene, autarke Zeitsteuerung, ist aber funktional mit dem 1400 Standard vergleichbar. So sieht der Comfort 1800 aus:

![image](https://user-images.githubusercontent.com/57875762/100102292-ae8c4380-2e63-11eb-9de9-a03124fc80dc.png)

ID 23602075 ist die Device ID des 20Nm SLDM Funkmotors, wo ich dir im Zuge der HUE Integration und Adapterversion 0.0.6 die Konfigfiles zugesendet habe. Müsste Ende 2019 gewesen sein, wo der neu in den Markt kam. Im HP wird auch der gesteuert wie ein Rollotron, also mit Autoelementen wie oben im Screenshot 1

![image](https://user-images.githubusercontent.com/57875762/100102887-7f2a0680-2e64-11eb-8a4a-9806aacf5710.jpeg)

**Comment by homecineplexx** [comment]
die 0.0.17 Version sollte die beiden Devices beinhalten

- 16234511 DuoFern-RolloTron-Comfort-1800/1805/1840

- 23602075 DuoFern-S-Line-Motor-Typ-SLDM-10/16-PZ
