### ISSUE TITLE
Will ioBroker.homepilot20 also support DuoFern 9471-1?

### ISSUE THREAD

**Issue by webtourhs** [homecineplexx/ioBroker.homepilot20#27]
DuoFerm 9471.1 is missing in the supportet devices

**Comment by funky4t** [comment]
@webtourhs 
Why is it missing? 9471-1 is the standard Rohrmotoraktor, that is already integrated in this adapter. This is how it shows up in my iobroker instance.

![9471-1](https://user-images.githubusercontent.com/57875762/103642035-e4d4dc80-4f52-11eb-8b14-9826d5347740.png)

Or is it missing in the description of supported devices? Then @homecineplexx just has to add it in the description of this adapter.

**Comment by homecineplexx** [comment]
> DuoFerm 9471.1 is missing in the supportet devices

hi
thanks for information. please try it out and tell me if it works please

**Comment by webtourhs** [comment]
Thank you for your comments. I don't have the device, but when I search for the device in the documentation
https://github.com/homecineplexx/ioBroker.homepilot20/blob/master/docs/de/doc_homepilot20_de.md
I don't find the 9471-1. So please add the description to the list.

**Comment by funky4t** [comment]
It is already there, just with Artikelnummer but missing Typenumber (pic2). I can assure device works perfectly well with this adapter 👌🏼

@homecineplexx You just have to add 9471 into that mentioned documentation. I pretty much guess 9471-2 is also working as datastructure is not different to 9471-1.

![image](https://user-images.githubusercontent.com/57875762/103646673-56fcef80-4f5a-11eb-99b1-aa9c6498499a.jpeg)

![image](https://user-images.githubusercontent.com/57875762/103646768-7d228f80-4f5a-11eb-9377-806c2d554f75.jpeg)

**Comment by homecineplexx** [comment]
done
