### ISSUE TITLE
Slatposition bei 35000662 fehlt der Datenpunkt

### ISSUE THREAD

**Issue by Snigga** [homecineplexx/ioBroker.homepilot20#33]
Hallo leider habe ich bei deviceNumber "35000662" den Datenpunkt Slatposition nicht. Habe ich irgendwas übersehen?

**Comment by homecineplexx** [comment]
hallo
ist das noch immer so???

**Comment by Snigga** [comment]
Leider nicht. Habe nur  homepilot20.0.*.Position  Datenpunkt. Aber nicht die Datenpunkte für INC_CMD und DEC_CMD Kommandos . (Für den Winkel der Lamellen von Jalousien zu verändern.)

**Comment by homecineplexx** [comment]
ok, das schau ich mir an!!!

**Comment by homecineplexx** [comment]
bitte versuch die version 0.0.30 da sollte das behoben sein.

wenn nicht, dann mach folgendes
1) homepilot20 instanz stoppen
2) kompletten datenpunkt-baum von homepilot20 löschen
3) homepilot20 instanz starten

bitte gib mir feedback
