### ISSUE TITLE
Immer wiederkehrender Logeintrag

### ISSUE THREAD

**Issue by meicker** [homecineplexx/ioBroker.homepilot20#34]
| Transmitter  sensors -> Cannot connect to Homepilot:  {"statusCode":500,"body":"<html>\r\n<head><title>500  Internal Server  Error</title></head>\r\n<body>\r\n<center><h1>500  Internal Server  Error</h1></center>\r\n<hr><center>nginx/1.17.1</center>\r\n</body>\r\n</html>\r\n","headers":{"server":"nginx/1.17.1","date":"Mon,  12 Jul 2021 21:19:26  GMT","content-type":"text/html","content-length":"177","connection":"close"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"192.168.1.180","port":80,"hostname":"192.168.1.180","hash":null,"search":"?devtype=Transmitter","query":"devtype=Transmitter","pathname":"/v4/devices","path":"/v4/devices?devtype=Transmitter","href":"http://192.168.1.180/v4/devices?devtype=Transmitter"},"method":"GET","headers":{"0":{},"1":{"Content-Type":"application/json"}}}}
-- | --

javascript.0 | 2021-07-12 23:21:38.126 | error | Error in request callback: SyntaxError: Unexpected token < in JSON at position 0
-- | -- | -- | --

**Comment by homecineplexx** [comment]
dann solltest du schauen, ob dein Rademacher Homepilot bzw die Bridge unter der von dir eingerichteten IP auch wirklich erreichbar ist!

und wenns mal nicht so ist, kann es sein, das dein Netzwerk oder das Device nicht erreichbar ist!
