### ISSUE TITLE
State Values werden mit falschen Datentypen belegt

### ISSUE THREAD

**Issue by kaeptnkessl** [homecineplexx/ioBroker.homepilot20#36]
**Describe the bug**  
Beim Start und jedem Sync des Adapters wird folgendes ins Log File geschrieben (Auszug):
_2021-08-11 23:35:08.624 - info: homepilot20.0 (17653) State value to set for "homepilot20.0.Actuator.1010016-35000662.deviceGroup" has to be type "string" but received type "number"
2021-08-11 23:35:08.625 - info: homepilot20.0 (17653) State value to set for "homepilot20.0.Actuator.1010016-35000662.did" has to be type "string" but received type "number"
2021-08-11 23:35:09.352 - info: homepilot20.0 (17653) State value to set for "homepilot20.0.Scene.5.active" has to be type "boolean" but received type "number"
2021-08-11 23:35:09.352 - info: homepilot20.0 (17653) State value to set for "homepilot20.0.Scene.5.isExecutable" has to be type "boolean" but received type "number"_
Diese Information wird für jeden Aktor und jede Szene ausgegeben und überflutet damit das Logfile.

**Versions:**  
 - Adapter version: v0.0.25
 - JS-Controller version: 3.3.15
 - Node version: v12.22.4
 - Operating system: Raspbian GNU/Linux 10 (buster)
 - IOBroker Admin: 5.1.23
 - Homepilot Version: 5.3.24 (Rademacher Homepilot 2)
 - DuoFern Version: 0.10

**Additional context**  
An sich funktioniert alles, was ich bisher getestet habe wunderbar. Rollläden lassen sich steuern und der Umweltsensor lässt sich auslesen. Danke dafür, das ist echt eine super Sache. Nur das hier gemeldete Thema mit dem Logfile stört irgendwie.

**Comment by homecineplexx** [comment]
könntest du mir bitte von dem jeweiligen Objekt
-) deviceGroup
-) did
-) active
-) isExecutable

Sowas zeigen
![image](https://user-images.githubusercontent.com/43374575/129138747-1321e018-5156-4f5c-bb21-7ffa554da1c5.png)

**Comment by homecineplexx** [comment]
@kaeptnkessl wundert mich nicht, du hast auch noch die alten strukturen

du mußt folgendes machen

-) Homepilot20 Instanz stoppen
-) die gesamten Homepilot20 Objekte löschen (ALLE)
-) Homepilot20 Adapter auf die neueste Version (sofern nicht vorhanden) updaten
-) Homepilot20 Instanz wieder starten

dann sollte zb das active einer Szene so aussehen:
`{
  "type": "state",
  "common": {
    "name": "active 5008",
    "desc": "active stored in homepilot for scene 5008",
    "type": "number",
    "role": "switch",
    "def": 0,
    "read": true,
    "write": true
  },
  "native": {},
  "from": "system.adapter.homepilot20.0",
  "user": "system.user.admin",
  "ts": 1628742331661,
  "_id": "homepilot20.0.Scene.5008.active",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by kaeptnkessl** [comment]
Danke! Das hat das Problem gelöst :thumbsup:

**Comment by Uli1701** [comment]
Hallo Chris,

vielen Dank für Deinen tollen Adapter. Die letzten Updates haben die String/Number Thematik auch bei mir beseitigt.
Leider habe ich weiterhin bei den Attributen der Sensoren jede Menge Fehlermeldungen im Log:
Beispiel:
![image](https://user-images.githubusercontent.com/86850865/129321985-7a448009-5bb4-490e-95d3-21ec90073b41.png)

Details zum Objekt:
{
  "type": "state",
  "common": {
    "name": "MOTION_DETECTION_MEA-timestamp",
    "desc": "name stored in homepilot for device 1010173",
    "role": "value.datetime",
    "read": true,
    "def": "",
    "min": -1
  },
  "native": {},
  "from": "system.adapter.homepilot20.0",
  "user": "system.user.admin",
  "ts": 1628839591154,
  "_id": "homepilot20.0.Sensor.1010173-32501772.Attribute.MOTION_DETECTION_MEA",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by homecineplexx** [comment]
Hallo Uli1701 

ich hab ein Problem mit dem Bewegungsmelder gefunden und dies hoffentlich (nach meinen Tests) auch gefixt. bitte schau dir das Readme an und mach einen upgrade auf 0.0.31

lg
