### ISSUE TITLE
Many warnings in the log

### ISSUE THREAD

**Issue by ouch2607** [homecineplexx/ioBroker.homepilot20#37]
I have many warnings in my log from the homepilot adapter. It really spams my log. Otherwise the adapter seems to work as it should.
I don't know, if there is any connection, but i noticed it not before i updated to admin 5 surface.
Homepilot-Adapter Version 0.0.29
Screenshot of my log:
![Unbenannt3](https://user-images.githubusercontent.com/89692697/131218934-d5e68840-1e63-4810-8193-f20ce738ed94.png)

**Comment by homecineplexx** [comment]
please do following:
1) stop the homepilot20 instanz
2) delete the complete Object tree of homepilot20
3) start the homepilot20 instanz 

and you will see, that there are no warnings anymore!
