### ISSUE TITLE
No Attributes available for Troll Basis DuoFern 36500172

### ISSUE THREAD

**Issue by hagge2000** [homecineplexx/ioBroker.homepilot20#39]
I'm using homepilot20 0.0.31 and have connected different actuators to my homepilot. For the Troll Basis DuoFern 36500172 I don't see the attributes like AUTO_MODE_CFG, DAWN_AUTO_CFG,...
Could you please add? Let me know if you need more details.

**Comment by homecineplexx** [comment]
please send me the output of: 

http://<homepilot-ip>/devices/<device-Id>

**Comment by homecineplexx** [comment]
so maybe your problem isnt really a problem because after 1 month....
