### ISSUE TITLE
Homepilot20 stürzt öfters ab

### ISSUE THREAD

**Issue by Bibo13** [homecineplexx/ioBroker.homepilot20#4]
sorry close war ein Fehler deshalb neuer Issue

*  | starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.homepilot20, node: v8.16.1
-- | --

host.Elzershark | 2019-10-01 15:47:58.819 | error | instance system.adapter.homepilot20.0 terminated with code 0 (OK)
-- | -- | -- | --
host.Elzershark | 2019-10-01 15:47:58.819 | error | Caught by controller[0]:     at emitNone (events.js:111:20)
host.Elzershark | 2019-10-01 15:47:58.818 | error | Caught by controller[0]:     at Object.onceWrapper (events.js:313:30)
host.Elzershark | 2019-10-01 15:47:58.817 | error | Caught by controller[0]:     at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1085:12)
host.Elzershark | 2019-10-01 15:47:58.816 | error | Caught by controller[0]:     at Request.emit (events.js:211:7)
host.Elzershark | 2019-10-01 15:47:58.816 | error | Caught by controller[0]:     at emitOne (events.js:116:13)
host.Elzershark | 2019-10-01 15:47:58.815 | error | Caught by controller[0]:     at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1163:10)
host.Elzershark | 2019-10-01 15:47:58.814 | error | Caught by controller[0]:     at Request.emit (events.js:214:7)
host.Elzershark | 2019-10-01 15:47:58.814 | error | Caught by controller[0]:     at emitTwo (events.js:126:13)
host.Elzershark | 2019-10-01 15:47:58.813 | error | Caught by controller[0]:     at Request.self.callback (/opt/iobroker/node_modules/request/request.js:186:22)
host.Elzershark | 2019-10-01 15:47:58.812 | error | Caught by controller[0]:     at Request._callback (/opt/iobroker/node_modules/iobroker.homepilot20/main.js:1727:15)
host.Elzershark | 2019-10-01 15:47:58.811 | error | Caught by controller[0]: ReferenceError: unreach is not defined
homepilot20.0 | 2019-10-01 15:47:58.756 | error | Adapter will be stopped
homepilot20.0 | 2019-10-01 15:47:58.756 | info | terminating homepilot20 adapter
homepilot20.0 | 2019-10-01 15:47:58.755 | error | ReferenceError: unreach is not defined     at Request._callback (/opt/iobroker/node_modules/iobroker.homepilot20/main.js:1727:15)     at Request.self.callback (/opt/iobroker/node_modules/request/reque
homepilot20.0 | 2019-10-01 15:47:58.754 | error | uncaught exception: unreach is not defined
homepilot20.0 | 2019-10-01 15:47:58.754 | warn | Read  Transmitter/additional info -> Cannot connect to Homepilot:  {"statusCode":502,"body":"<!DOCTYPE  html>\n<html>\n<head>\n<title>Error</title>\n<style>\n     body {\n        width: 35em;\n        mar

latest Version 0.0.1
Node.js: v8.16.1
NPM: 6.4.1

**Comment by homecineplexx** [comment]
please update to version 0.0.2 because i have fixed a lot of problems and i think this is one of them. one variable wasn't declared.
if the issue doesn't occure, please report

**Comment by Bibo13** [comment]
I think after the update to 0.0.2, the crashes are gone. I cross the fingers. 
thanks for your work
