### ISSUE TITLE
Log: State value to set for "homepilot20.0.Actuator.27-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"

### ISSUE THREAD

**Issue by MarsEnz** [homecineplexx/ioBroker.homepilot20#41]
Hi, I get in the log that several data points are of type "boolean" but receive "string" data.

**Describe the bug**  
Debug info in log

**Screenshots & Logfiles**  

`<html>
<body>

homepilot20.0 | 2021-12-01 22:48:45.453 | info | State value to set for "homepilot20.0.Actuator.26-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
-- | -- | -- | --
homepilot20.0 | 2021-12-01 22:48:45.453 | info | State value to set for "homepilot20.0.Actuator.26-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.452 | info | State value to set for "homepilot20.0.Actuator.26-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.452 | info | State value to set for "homepilot20.0.Actuator.26-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.452 | info | State value to set for "homepilot20.0.Actuator.26-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.451 | info | State value to set for "homepilot20.0.Actuator.28-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.451 | info | State value to set for "homepilot20.0.Actuator.28-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.451 | info | State value to set for "homepilot20.0.Actuator.28-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.451 | info | State value to set for "homepilot20.0.Actuator.28-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.450 | info | State value to set for "homepilot20.0.Actuator.28-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.450 | info | State value to set for "homepilot20.0.Actuator.29-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.450 | info | State value to set for "homepilot20.0.Actuator.29-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.449 | info | State value to set for "homepilot20.0.Actuator.29-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.449 | info | State value to set for "homepilot20.0.Actuator.29-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.449 | info | State value to set for "homepilot20.0.Actuator.29-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.449 | info | State value to set for "homepilot20.0.Actuator.1-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.448 | info | State value to set for "homepilot20.0.Actuator.1-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.448 | info | State value to set for "homepilot20.0.Actuator.1-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.447 | info | State value to set for "homepilot20.0.Actuator.1-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.447 | info | State value to set for "homepilot20.0.Actuator.1-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.447 | info | State value to set for "homepilot20.0.Actuator.27-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.445 | info | State value to set for "homepilot20.0.Actuator.27-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.444 | info | State value to set for "homepilot20.0.Actuator.27-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.444 | info | State value to set for "homepilot20.0.Actuator.27-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.444 | info | State value to set for "homepilot20.0.Actuator.27-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.437 | info | State value to set for "homepilot20.0.Actuator.25-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.437 | info | State value to set for "homepilot20.0.Actuator.25-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.437 | info | State value to set for "homepilot20.0.Actuator.25-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.437 | info | State value to set for "homepilot20.0.Actuator.25-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.436 | info | State value to set for "homepilot20.0.Actuator.25-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.435 | info | State value to set for "homepilot20.0.Actuator.24-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.435 | info | State value to set for "homepilot20.0.Actuator.24-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.435 | info | State value to set for "homepilot20.0.Actuator.24-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.434 | info | State value to set for "homepilot20.0.Actuator.24-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.434 | info | State value to set for "homepilot20.0.Actuator.24-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:45.037 | info | State value to set for "homepilot20.0.Actuator.29-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.037 | info | State value to set for "homepilot20.0.Actuator.29-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.033 | info | State value to set for "homepilot20.0.Actuator.28-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.033 | info | State value to set for "homepilot20.0.Actuator.28-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.032 | info | State value to set for "homepilot20.0.Actuator.27-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.032 | info | State value to set for "homepilot20.0.Actuator.27-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.029 | info | State value to set for "homepilot20.0.Actuator.26-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.029 | info | State value to set for "homepilot20.0.Actuator.26-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.028 | info | State value to set for "homepilot20.0.Actuator.25-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.028 | info | State value to set for "homepilot20.0.Actuator.25-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.028 | info | State value to set for "homepilot20.0.Actuator.24-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.027 | info | State value to set for "homepilot20.0.Actuator.24-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.027 | info | State value to set for "homepilot20.0.Actuator.1-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:45.026 | info | State value to set for "homepilot20.0.Actuator.1-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.455 | info | State value to set for "homepilot20.0.Actuator.26-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.455 | info | State value to set for "homepilot20.0.Actuator.26-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.455 | info | State value to set for "homepilot20.0.Actuator.26-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.454 | info | State value to set for "homepilot20.0.Actuator.26-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.453 | info | State value to set for "homepilot20.0.Actuator.26-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.453 | info | State value to set for "homepilot20.0.Actuator.27-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.452 | info | State value to set for "homepilot20.0.Actuator.27-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.452 | info | State value to set for "homepilot20.0.Actuator.27-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.452 | info | State value to set for "homepilot20.0.Actuator.27-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.445 | info | State value to set for "homepilot20.0.Actuator.27-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.445 | info | State value to set for "homepilot20.0.Actuator.28-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.444 | info | State value to set for "homepilot20.0.Actuator.28-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.444 | info | State value to set for "homepilot20.0.Actuator.28-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.444 | info | State value to set for "homepilot20.0.Actuator.28-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.443 | info | State value to set for "homepilot20.0.Actuator.28-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.442 | info | State value to set for "homepilot20.0.Actuator.1-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.442 | info | State value to set for "homepilot20.0.Actuator.1-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.442 | info | State value to set for "homepilot20.0.Actuator.1-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.441 | info | State value to set for "homepilot20.0.Actuator.1-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.441 | info | State value to set for "homepilot20.0.Actuator.1-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.441 | info | State value to set for "homepilot20.0.Actuator.24-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.440 | info | State value to set for "homepilot20.0.Actuator.24-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.440 | info | State value to set for "homepilot20.0.Actuator.24-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.439 | info | State value to set for "homepilot20.0.Actuator.24-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.439 | info | State value to set for "homepilot20.0.Actuator.24-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.438 | info | State value to set for "homepilot20.0.Actuator.29-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.438 | info | State value to set for "homepilot20.0.Actuator.29-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.438 | info | State value to set for "homepilot20.0.Actuator.29-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.437 | info | State value to set for "homepilot20.0.Actuator.29-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.436 | info | State value to set for "homepilot20.0.Actuator.29-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.434 | info | State value to set for "homepilot20.0.Actuator.25-23602075.Attribute.DUSK_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.433 | info | State value to set for "homepilot20.0.Actuator.25-23602075.Attribute.DAWN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.433 | info | State value to set for "homepilot20.0.Actuator.25-23602075.Attribute.SUN_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.433 | info | State value to set for "homepilot20.0.Actuator.25-23602075.Attribute.TIME_AUTO_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.430 | info | State value to set for "homepilot20.0.Actuator.25-23602075.Attribute.AUTO_MODE_CFG" has to be type "boolean" but received type "string"
homepilot20.0 | 2021-12-01 22:48:33.085 | info | State value to set for "homepilot20.0.Actuator.29-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.084 | info | State value to set for "homepilot20.0.Actuator.29-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.078 | info | State value to set for "homepilot20.0.Actuator.28-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.077 | info | State value to set for "homepilot20.0.Actuator.28-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.075 | info | State value to set for "homepilot20.0.Actuator.27-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.074 | info | State value to set for "homepilot20.0.Actuator.27-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.071 | info | State value to set for "homepilot20.0.Actuator.26-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.070 | info | State value to set for "homepilot20.0.Actuator.26-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.067 | info | State value to set for "homepilot20.0.Actuator.25-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.066 | info | State value to set for "homepilot20.0.Actuator.25-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.060 | info | State value to set for "homepilot20.0.Actuator.24-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.059 | info | State value to set for "homepilot20.0.Actuator.24-23602075.deviceGroup" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.052 | info | State value to set for "homepilot20.0.Actuator.1-23602075.did" has to be type "string" but received type "number"
homepilot20.0 | 2021-12-01 22:48:33.051 | info | State value to set for "homepilot20.0.Actuator.1-23602075.deviceGroup" has to be type "string" but received type "number"

</body>
</html>`

**Versions:**  
 - Adapter version: <v0.0.18>
 - JS-Controller version: <js-controller-version> 
![image](https://user-images.githubusercontent.com/95384789/144320801-946c3bd1-ff9e-45b0-aaaf-9377f9d98b37.png)
 - Node version: <v12.22.6>
  - Operating system: <os-name>

**Comment by homecineplexx** [comment]
Before you write an issue, you should read the overview page of the version and think about it!!!
