### ISSUE TITLE
Error Set Slatposition

### ISSUE THREAD

**Issue by Snigga** [homecineplexx/ioBroker.homepilot20#42]
<html>
<body>

homepilot20.0 | 2021-12-18 14:22:46.359 | error | deviceNumber is not defined
-- | -- | -- | --
homepilot20.0 | 2021-12-18 14:22:46.358 | error | ReferenceError: deviceNumber is not defined at controlHomepilot (/opt/iobroker/node_modules/iobroker.homepilot20/main.js:127:7) at Object.stateChange (/opt/iobroker/node_modules/iobroker.homepilot20/main.js:43:4) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5706:41) at processImmediate (internal/timers.js:464:21)
homepilot20.0 | 2021-12-18 14:22:46.354 | error | uncaught exception: deviceNumber is not defined
homepilot20.0 | 2021-12-18 14:22:46.351 | debug | id: homepilot20.0.Actuator.1010005-35000662.slatposition, command: 50

</body>
</html>

**Comment by homecineplexx** [comment]
should be fixed with 0.0.35
