### ISSUE TITLE
Name der Objekte falsch / wird nicht geändert

### ISSUE THREAD

**Issue by darkman242** [homecineplexx/ioBroker.homepilot20#46]
Hi, wenn ich ein Gerät in der Bridge hinzufüge wird dies korrekt im ioBroker angelgt. Dabei wird der Name des Gerätes in die Beschreibung des Objektes mit aufgenommen. Ändere ich die Namen des Gerätes in der Bridge wird der Name als Objektname nicht geändert.

Es wäre in meinen Augen sinnvoll den Namen des Gerätes nicht mit in den Objektnamen aufzunehmen. Ein Objekt 'Name' mit dem aktuellen Namen exisitiert ja.

![image](https://user-images.githubusercontent.com/46793576/155522673-3c76ca05-736e-4424-96c8-22d56f95b3ea.png)

**Comment by homecineplexx** [comment]
Werde ich ausbauen...hast du natürlich recht. 
Dachte mir nur, den Namen vergibt man wahrscheinlich 1 Mal und dann passt dieser eh und wenn man viele Devices hat, hätte man dann ein bissl eine Übersicht ohne dass man alles aufklappen muss

**Comment by homecineplexx** [comment]
done in 0.0.34

damit es funktioniert:
-) Upgrade auf 0.0.34
-) Instanz stoppen
-) alle Actuator, Sensor, Scene und Transmitter löschen (komplette Objektbäume)
-) Instanz starten
