### ISSUE TITLE
uncaught exception: Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by darkman242** [homecineplexx/ioBroker.homepilot20#47]
<html>
<body>

homepilot20.0 | 2022-02-28 10:15:06.058 | info | starting. Version 0.0.32 (non-npm: homecineplexx/ioBroker.homepilot20#a56acd4b7a5b2498201de8a2b6976e8f0e49de1b) in /opt/iobroker/node_modules/iobroker.homepilot20, node: v14.19.0, js-controller: 4.0.15
-- | -- | -- | --
homepilot20.0 | 2022-02-28 10:14:34.110 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
homepilot20.0 | 2022-02-28 10:14:34.110 | info | terminating
homepilot20.0 | 2022-02-28 10:14:34.110 | error | Adapter will be stopped
homepilot20.0 | 2022-02-28 10:14:34.109 | info | terminating homepilot20 adapter
homepilot20.0 | 2022-02-28 10:14:34.106 | error | Cannot read property 'toString' of null
homepilot20.0 | 2022-02-28 10:14:34.106 | error | TypeError: Cannot read property 'toString' of null at Object.stateChange (/opt/iobroker/node_modules/iobroker.homepilot20/main.js:42:50) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5375:56) at processImmediate (internal/timers.js:464:21)
homepilot20.0 | 2022-02-28 10:14:34.098 | error | uncaught exception: Cannot read property 'toString' of null

</body>
</html>

**Comment by homecineplexx** [comment]
hey
do you have more information for me?
what have you done? changed a special parameter of a device??

**Comment by darkman242** [comment]
die Meldung ist bisher nur einmal aufgetreten, ohne irgendeine Steuerung über ioBroker ... ich werde weiter beobachten

**Comment by homecineplexx** [comment]
nachdem es nicht öfter gekommen ist, schließe ich das ticket
