### ISSUE TITLE
Homepilot reports Errors

### ISSUE THREAD

**Issue by Bibo13** [homecineplexx/ioBroker.homepilot20#5]
After updating the Adapter is HP now Reporting Errors an fill the Log up.
Do we have a chance to suppress this? Or can we have a DP to control the responsible devices?
Maybe that's the case and I have not seen it.

homepilot20.0 | 2019-10-02 12:48:11.597 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:47:59.534 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:47:47.553 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:47:35.532 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:47:23.622 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:47:11.532 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:46:59.493 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:46:47.517 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:46:35.477 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:46:23.473 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:46:11.403 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:45:59.419 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:45:47.423 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:45:35.418 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:45:23.383 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:45:11.411 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:44:59.377 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:44:47.387 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:44:35.408 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:44:23.365 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:44:11.344 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:43:59.372 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:43:47.417 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:43:35.302 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:43:23.316 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:43:11.382 | warn | Homepilot Device 1010006 reports an error
homepilot20.0 | 2019-10-02 12:42:59.256 | warn | Homepilot Device 1010006 reports an error

**Comment by homecineplexx** [comment]
please set the log-level to debug and post the logs.
thanks!

**Comment by Bibo13** [comment]
i have done this. what do you need. the log after new start?

**Comment by homecineplexx** [comment]
what kind of device is it?
do you hava a deviceNumber from this type?
or  a link to the rademacher page?

**Comment by Bibo13** [comment]
found in the log some datas. please have a look
[homepilot_log.txt](https://github.com/homecineplexx/ioBroker.homepilot20/files/3681056/homepilot_log.txt)

**Comment by Bibo13** [comment]
it's a
DuoFern-RolloTron-Standard-1400/1405/1440: Wohnzimmer Klein (Device ID 1010006)

**Comment by Bibo13** [comment]
i will leave for a while. back a 5:30pm

**Comment by homecineplexx** [comment]
> found in the log some datas. please have a look
> [homepilot_log.txt](https://github.com/homecineplexx/ioBroker.homepilot20/files/3681056/homepilot_log.txt)

i can't see any error in your homepilot_log.txt

**Comment by Bibo13** [comment]
there is also not the error occurred inside. he only appears sporadically. the problem is, if you leave the adapter on debug but then a lot of data will be written to the log. therefore yes synonymous my question is there for the error a data point with which I could alam. the response time to the error would be shorter and I could see in the rademacher homepilot if he indicates an error. Incidentally, if you follow the facebook group you have the post of eva weber over the HP-log. I asked Rademacher. the solution is to rename the log file ending tgz and then unzip it.
so now i'm out for a while.

**Comment by Wilhelm111** [comment]
how can I update the adapter to 0.02 without losing the objects. I don't want to reinstall the adapter because it is not on the updatelist.

**Comment by Bibo13** [comment]
I caught the error.
019-10-02 17: 23: 12.359 - warn: homepilot20.0 Homepilot Device 1010001 reports an error

he should be in the attached logfile.
[homepilot_log.txt](https://github.com/homecineplexx/ioBroker.homepilot20/files/3681898/homepilot_log.txt)

**Comment by Wilhelm111** [comment]
Solved: Installation from url will update if Adapter is installed

**Comment by Bibo13** [comment]
oh you are fast. thanks

**Comment by homecineplexx** [comment]
> I caught the error.
> 019-10-02 17: 23: 12.359 - warn: homepilot20.0 Homepilot Device 1010001 reports an error
> 
> he should be in the attached logfile.
> [homepilot_log.txt](https://github.com/homecineplexx/ioBroker.homepilot20/files/3681898/homepilot_log.txt)

so i checked your logs and i can see, that one of your actuators (shutter) signals an error: obstacle detection
so i changed the log to loglevel info and from version 0.0.3 you can see the actuator error messages in the datapoint

**Comment by homecineplexx** [comment]
> how can I update the adapter to 0.02 without losing the objects. I don't want to reinstall the adapter because it is not on the updatelist.

there is an npm version 0.0.3 available since now! have fun
