### ISSUE TITLE
9499 DueFern Sun/Win Sensor

### ISSUE THREAD

**Issue by spitzea** [homecineplexx/ioBroker.homepilot20#50]
Is it planned to integrate the new Sun/Win Sensor (9499) into the adapter? 
https://www.rademacher.de/shop/rollladen-sonnenschutz/sensoren/duofern-sonnen-windsensor-9499

I received it today and registered in the homepilot and just noticed that it is not yet supported by the adapter.

I would be very happy if this can be realized and of course support if I can provide data.

http://homepilot.local/v4/devices?devtype=Sensor

{"response":"get_meters","meters":[{"description":"Ihre Gerätebeschreibung",
"deviceGroup":3,"did":1010045,"automations":[30,50],"readings":{"sun_detected":false,"wind_detected":false},"timestamp":1652730334,"iconSetInverted":0,"iconSet":{"k":"iconset19"},"name":"DuoFern Sonne-/Windsensor","statusValid":true,"deviceNumber":"32004464","uid":"a901c2_1","visible":true},]}

**Comment by homecineplexx** [comment]
i can do this

**Comment by spitzea** [comment]
... and here in addition detailed information about the device itself:

http://homepilot.local/devices/1010045

{"error_description":"OK","error_code":0,"payload":{"device":{"capabilities":[{"name":"SUN_STOP_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"SUN_STOP_EVT","read_only":true,"timestamp":-1},{"name":"VERSION_CFG","value":"1.1-1","read_only":false,"timestamp":1652759215},{"name":"PROD_CODE_DEVICE_LOC","value":"32004464","read_only":false,"timestamp":-1},{"name":"REACHABILITY_EVT","value":"true","read_only":true,"timestamp":1652759215},{"name":"NAME_DEVICE_LOC","value":"DuoFern Sonne-/Windsensor","read_only":false,"timestamp":1652687458},{"name":"PROT_ID_DEVICE_LOC","value":"a901c2_1","read_only":false,"timestamp":-1},{"name":"INTF_ID_DEVICE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"SUN_START_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"WIND_START_EVT","read_only":true,"timestamp":-1},{"name":"WIND_DETECTION_MEA","value":"false","read_only":false,"timestamp":1652759215},{"name":"ICONSET_LOC","value":"iconset19","read_only":false,"timestamp":1652687458},{"name":"SUN_START_EVT","read_only":true,"timestamp":-1},{"name":"SUN_DETECTION_MEA","value":"false","read_only":false,"timestamp":-1},{"name":"DEVICE_TYPE_LOC","value":"3","read_only":false,"timestamp":-1},{"name":"ICONSET_INV_LOC","value":"false","read_only":false,"timestamp":-1},{"name":"SUN_START_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"WIND_STOP_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"PAIRING_CONFIRMED_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"ID_DEVICE_LOC","value":"1010045","read_only":false,"timestamp":-1},{"name":"PROTOCOL_ID_CFG","value":"a901c2","read_only":false,"timestamp":-1},{"name":"WIND_STOP_EVT","read_only":true,"timestamp":-1},{"name":"WIND_START_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"SUN_STOP_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"WIND_START_EVT_PUSH_TEXT","value":"","read_only":false,"timestamp":-1},{"name":"VIS_DEVICE_LOC","value":"true","read_only":false,"timestamp":-1},{"name":"WIND_STOP_EVT_PUSH_ENABLED","value":"false","read_only":false,"timestamp":-1},{"name":"DESCR_DEVICE_LOC","value":"Ihre Gerätebeschreibung","read_only":false,"timestamp":1652687458}],"scenes":[]}}}

Thank you in advance!!!

**Comment by spitzea** [comment]
I do not want to annoy you, but could you estimate when you can add the new Sun/Win Sensor (9499) into the adapter?

**Comment by homecineplexx** [comment]
try version 0.0.42 should work
