### ISSUE TITLE
Neue Datenpunkte bezüglich Scenen

### ISSUE THREAD

**Issue by Snigga** [homecineplexx/ioBroker.homepilot20#51]
Es wäre hilfreich, wenn man entweder einen Auslöser der Scene nicht nur als generellen Auslöser hätte, sondern auch mit der Option zB. Auslöser Sonne, Wind etc.  und der Adapter prüft dann, ob alle Geräte die Automatik Sonne, Wind etc.  auf true gesetzt sind. Geräte mit true werden ausgelöst, die mit false nicht. 

Dies wäre eine Erweiterung der homepilot20.0.Scene.XXXX.execute Button.

Wäre das möglich?

**Comment by homecineplexx** [comment]
Also die zusätzlichen Informationen für Szenen sollte es schon geben.

Du kannst natürlich die Szene triggern und das wird dann zum Homepilot geschickt. Und der HP macht dann eh die Logik

**Comment by Snigga** [comment]
Informationen werden angezeigt. Stimmt. Das der HP dann eh die Logik macht stimmt leider nicht, da über dem iobroker nur der Befehl Scene ausführen übermittelt werden kann. Den Zusatz das der Grund zB Sonne war, kann nicht übermittelt werden. Deshalb findet die Logik keine Anwendung. Oder habe ich was übersehen.

**Comment by homecineplexx** [comment]
Das kannst du dir aber eigentlich ganz leicht im ioBroker nachbauen. du brauchst die ja nur alle Geräte holen die zB WIND auf Automatik haben und dann machst du etwas
