### ISSUE TITLE
npm WARN skipping integrity check for git dependency ssh://git@github.com/homecineplexx/ioBroker.homepilot20.git 

### ISSUE THREAD

**Issue by Garfield081** [homecineplexx/ioBroker.homepilot20#52]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Garfield081** [comment]
Installing https://www.npmjs.com/package/iobroker.homepilot20/v/0.0.32... (System call)

npm WARN tar TAR_ENTRY_INVALID checksum failure

npm WARN tar TAR_ENTRY_INVALID checksum failurenpm WARN tar TAR_ENTRY_INVALID checksum failure

npm WARN tar TAR_ENTRY_INVALID checksum failurenpm WARN tar TAR_ENTRY_INVALID checksum failure

npm WARN tar TAR_ENTRY_INVALID checksum failurenpm WARN tar TAR_ENTRY_INVALID checksum failure

npm WARN tar TAR_ENTRY_INVALID checksum failurenpm WARN tar TAR_ENTRY_INVALID checksum failure

npm WARN tar TAR_ENTRY_INVALID checksum failurenpm WARN tar TAR_ENTRY_INVALID checksum failurenpm WARN tar TAR_ENTRY_INVALID checksum failure

host.iobroker Cannot install https://www.npmjs.com/package/iobroker.homepilot20/v/0.0.32: 1

ERROR: Process exited with code 25

**Comment by homecineplexx** [comment]
Ich hab keine Ahnung, warum du eine v 0.0.32 installierst, wenns schon die v 0.0.42 gibt.
wie du sie installiert hast, weiss ich leider auch nicht.

und mit der aussage von wegen "die admin oberfläche um ip einzugeben" fehlt....kann auch keiner was anfangen.

Vielleicht versuchst du dein Problem strukturiert anzugehen und auch zu beschreiben, dann könnte man dir eventuell auch helfen! Dafür gibts auch als kleines Template, dieses Teil, was du ganz oben schon aus versehen gepostet hast....

**Comment by Garfield081** [comment]
sorry hatte ich vergessen ... 
aber leuft inzwischen einwandfrei 

die 3er Version sei die warnings auch in der 4 er kommen 

ihr solltet allerdings in der Anleitung darauf hinweisen das die instans noch mit dem +im Modul generirt werden muss .....

darauf wurde ichnvon einem anderen user hingewiesen

**Comment by homecineplexx** [comment]
Sorry, das weiß man, dass wenn man einen Adapter über die Katze und benutzerdefiniert installiert, dass dann nicht automatisch eine Instanz generiert wird. 
Doku lesen!!!
