### ISSUE TITLE
Implementiere run-Status für Aktoren

### ISSUE THREAD

**Issue by JilliOe** [homecineplexx/ioBroker.homepilot20#54]
Hi,

danke für den Adapter, endlich die letzten Rollläden integriert.

Liefert die REST-API die Möglichkeit abzufragen, ob ein Rollladen gerade fährt?
Ein solcher Datenpunkt wäre sehr praktisch, wenn der Rollladen über eine Taste (bspw. Homematic)  hochfahren und stoppen soll: wenn fährt = stop, sonst = hoch.
Wäre soetwas machbar?

Vielen Dank im Voraus,
ke

verwende über Homepilot (5.5.10) 2x Rademacher RolloTron Basis DuoFern 1200-UW (v1.3-2) und 2x Rademacher RolloTron Standard DuoFern 2510-UW (v1.3-2), funktioniert gut

**Comment by homecineplexx** [comment]
Hallo
Sorry, sowas gibts leider nicht, du könntest dir da nur selbst etwas schnitzen.
lg

**Comment by JilliOe** [comment]
Alles klar, vielen Dank und frohe Feiertage
