### ISSUE TITLE
Kein Bug - eine Anfrage - Fahrgeschwindigkeit

### ISSUE THREAD

**Issue by DJbanek** [homecineplexx/ioBroker.homepilot20#55]
Ich bin leider nur DAU und abreite mich seit Jahren in alles ein... Folgende Frage habe ich, weder Google, GitHub oder ChatGPT können helfen. Eventuell ist es auch nur ein Verständnisproblem:
Ich nutze mehrere 1200-UW und 1400-UW und die Bridge. Die 1400-UW können drei verschieden Geschwindigkeiten fahren, jedoch nur im Auto Modus. Dieser ist anscheinend nur über den HomePilot möglich.
Frage: Mit level.blind kann ich rauf/runter oder in Position fahren - gibt es einen command der die Geschwindigkeit ändert oder beeinflusst?

**Comment by DJbanek** [comment]
[https://forum.iobroker.net/assets/uploads/files/1621698445671-bildschirmfoto-2021-05-22-um-17.33.52.png](url)

Bei FHEM gibt es noch mehr Variablen... Kann man die noch ergänzen?

**Comment by homecineplexx** [comment]
Hallo
da ich ja selbst leider nicht jedes Device habe und somit auch nicht testen kann, weiß ich das natürlich nicht.
Kannst du diese Geschwindigkeiten irgendwie über die App oder den Homepilot auswählen? Wenn ja, mach mal ein Foto davon wie das aussieht.
man kann natürlich die Variablen eventuell anpassen...die Frage ist nur, was du damit machen möchtest. Möglicherweise machts ja keinen Sinn  bzw müßtest mir erklären was du mit welcher Variable machen willst. Manche davon solltest/könntest du schon haben im ioBroker unter Objekte. Zeig mal deine Baumstruktur!

**Comment by DJbanek** [comment]
Cool, danke für die Antwort. Ich unterstütze wo ich kann ;) Hier mal der Auszug aus dem Handbuch:
![2023-02-07](https://user-images.githubusercontent.com/80584667/217352551-fb6a6ce1-3280-4f12-8fb8-58be8f8f6c0d.png)

Also die drei Geschwindigkeiten gehen meines Erachtens nicht über Homepilot einzustellen. Allerdings habe ich nur die Bridge, glaube aber, dass auch beim Homepilot kein "Button" oder ähnliches vorhanden ist. Wie im Handbuch beschrieben, stellt man die direkt an der Hardware ein. Drückst du hier, drückst du da.
Für die Automatikfunktionen (da muss es eine für Zeit, Sonnenauf/untergang und Sonnenstand geben), würde der Homepilot diese Geschwindigkeit dann nehmen.
Gegoogelt habe ich, dass es die Parameter in FHEM geben muss und es damit funktioniert (siehe oben .png). dawnAutomatic usw...
Im manuellen Modus, also über die Variablen "position" oder "rauf "runter" usw. werden die Geschwindigkeiten nicht übernommen.
Ich bin mir jetzt unsicher, ob man jetzt einfach eine Variable wie "SunAutomatic" auf true setzen kann und dann wird "position" mit der eingestellten Geschwindigkeit gefahren.

Hier mal die aktuelle Ansicht, dass hilft aber nicht weiter, denke ich...
![2023-02-07 (1)](https://user-images.githubusercontent.com/80584667/217354803-735f992b-7b08-4cea-812d-a0e4d5c23345.png)

P.S. Die langsamste Geschwindigkeit ist wirklich sehr langsam und flüsterleise - deswegen habe ich extra nochmal von den 1200-UW auf die 1400-UW gewechselt.

**Comment by DJbanek** [comment]
Gäbe es eine Möglichkeit die Geschwindigkeiten zu implementieren? Kann ich irgendwie unterstützen?

**Comment by homecineplexx** [comment]
ich seh da leider keine möglichkeit die geschwindigkeit einzustellen...das macht das teil von selbst nehm ich an

**Comment by DJbanek** [comment]
Schade, dann werde ich mich wohl mit dem HomePilot auseinander setzen müssen -.-

**Comment by homecineplexx** [comment]
wenn man über den homepilot keine möglichkeit hat, die geschwindigkeit zu regeln, dann geht das so auch nicht

**Comment by homecineplexx** [comment]
Ich halte das implementieren von gewissen Parametern eher für sinnlos.
1tens werdens dann immer mehr und 2tens ist der ioBroker eigentlich dafür da um zentral alles zu steuern nicht extra auf den Geräten etwas einzustellen wie "SunAutomatic" und dann kommt ein neues Gerät dazu oder muss getauscht werden weils kaputt ist und dann funktioniert das erst wieder nicht.

das mit den Geschwindigkeiten kann ich leider nicht nachvollziehen
