### ISSUE TITLE
Compability check to firmware 5.7.15?

### ISSUE THREAD

**Issue by PottiMc** [homecineplexx/ioBroker.homepilot20#58]
This is just a short question since I didn't find anything in the closed issues and the adapter hasn't been updated for some time. Are ther any problems when updating the "SmartHomeBox" firmware to 5.7.15?

Sorry for asking but I don't want to break anything. You can close this issue after answering.

**Comment by FiraSenax** [comment]
Works for me also when the quiteness in here is disturbing

**Comment by PottiMc** [comment]
I can confirm it is working. Did the update 2 weeks ago. Will close this issue and thank you for your answer!
