### ISSUE TITLE
Welches Rademacher Gerät wird genau benötigt

### ISSUE THREAD

**Issue by adieball** [homecineplexx/ioBroker.homepilot20#61]
Hi

Mein Homepilot 2 hat das zeitliche gesegnet.
Nun hat Rademacher (wie so häufig) ja so einiges geändert. Ich lese hier zwar von "Bridge, etc", aber im Shop gibt es nur noch das "Gateway Premium" und einen Zigbee addon Stick.
diesen Stick habe ich ja schon in meinem jetziger HomePilot 2

Meine Frage:
Geht dieses "Gateway Premium" auch mit diesem Adapter?
Brauche ich dazu dann noch den Zigbee Stick oder kann ich den aktuellen nutzen oder brauche ich gar keinen (Laut Rademacher braucht man den für das Gateway Premium nur um HUE oder Tradfri einzubinden)
Gibt es irgendwo noch diese "günstige" Bridge zu kaufen und kann ich diese nutzen?

Sorry für all die Fragen

Andre

**Comment by adieball** [comment]
ach so, es geht um DuoFern-Troll-Comfort-5665 Geräte für Rolladen

**Comment by homecineplexx** [comment]
Hallo
ich kann dir nicht sagen, ob das diese Bridge ist oder nicht oder welche du genau dafür brauchst. 
was mein Adapter kann und welche Geräte alle inkludiert sind, siehst du in der Dokumentation.
