### ISSUE TITLE
HOMEPILOT - Rollladenmotor Premium smart m10 wird im ioBroker nicht erkannt an Smarthome-box von Rademacher

### ISSUE THREAD

**Issue by AHahne64** [homecineplexx/ioBroker.homepilot20#63]
HOMEPILOT - Rollladenmotor Premium smart m10 wird im ioBroker nicht erkannt an Smarthome-box von Rademacher

Ich habe hier eine [smarthome-box](https://service.rademacher.de/hc/de/categories/360001686013) (Bis Mai 2023 wurde die Zentrale unter dem Namen HomePilot vertrieben) von Rademacher an der sind insgesamt 13 Rolladen angeschlossen. - Firmware 5.7.15
Auf Grund eines defekten Motors habe ich den verbauten Aktor ([DuoFern Rohrmotor-Aktor UP 9471-1](https://service.rademacher.de/hc/de/sections/115001410209-DuoFern-Rohrmotor-Aktor-UP-9471-1)) gegen einen Rolladenmotor ([Rollladenmotor premium smart m10](https://de.homepilot-smarthome.com/produkte/rollladen-sonnenschutz/rohrmotore/rollladenmotor-premium-smart-m10)) ersetzt. Mit der Rademacher Zentrale funktioniert der Motor ohne Probleme. Im ioBroker wird dieses Gerät nicht angezeigt. ich habe auch bereits einmal den ioBroker neu installiert und dann den Rademacher Adapter hinzugefügt. Alle Motoren wurden angezeigt bis auf den neuen.

Vom Home Assistant wirtd er erkannt allerdings auch nur als generic devices. Bei den anderen Motoren oder Aktoren wird der genaue Typ angegeben. 

Ist es wohl möglich die neuen Motoren einzubinden?

**Versions:**  
 - Adapter version: 0.0.40 und 0.0.44
 - JS-Controller version: 5.0.16
 - Node version: v18.18.2
 - Operating system: linux - Debian 12

**Comment by homecineplexx** [comment]
Ja sicherlich kann man das machen, muss ich nur Zeit dazu finden und von
dir benötige ich Infos
LG Chris

AHahne64 ***@***.***> schrieb am Mi., 15. Nov. 2023, 17:31:

**Comment by AHahne64** [comment]
Hallo Chris,

das wäre super nett wenn du helfen würdest. Da habe ich Verständnis für das du Zeit finden muss.

Wie kann ich dir helfen? Würde ich gerne machen.

Gruß

Andreas

**Comment by homecineplexx** [comment]
Guten Morgen
ICh brauch zum einen den Output von dem hier  http://<ip vom der
smarthome-box>/v4/devices?devtype=Actuator und da musst du mir sagen,
welcher der Rollladenmotor ist und dann schauen wir mal weiter

glg chris

Am Mi., 15. Nov. 2023 um 20:23 Uhr schrieb AHahne64 <
***@***.***>:

**Comment by AHahne64** [comment]
{"response":"get_visible_devices","devices":[{"description":"Fenster Wohnzimmer 1 OG","deviceGroup":2,"did":1,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Fenster Wohnzimmer 1 OG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":100,"Position":100},"visible":true,"deviceNumber":"27601565","uid":"4958ef_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Tür Wohnzimmer 1 OG","deviceGroup":2,"did":2,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Tür Wohnzimmer 1 OG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":100,"Position":100},"visible":true,"deviceNumber":"27601565","uid":"494186_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Tür Esszimmer Groß 1 OG","deviceGroup":2,"did":3,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Tür Esszimmer Groß 1 OG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":100,"Position":100},"visible":true,"deviceNumber":"27601565","uid":"494aa0_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Fenster Esszimmer 1 OG","deviceGroup":2,"did":4,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Fenster Esszimmer 1 OG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":100,"Position":100},"visible":true,"deviceNumber":"35000662","uid":"426115_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Fenster Küche 1 OG","deviceGroup":2,"did":5,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Fenster Küche 1 OG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":100,"Position":100},"visible":true,"deviceNumber":"35000662","uid":"426291_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Bad 1 OG","deviceGroup":2,"did":7,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Bad 1 OG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":100,"Position":100},"visible":true,"deviceNumber":"35000662","uid":"42ad78_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Esszimmer EG","deviceGroup":2,"did":8,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Esszimmer EG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":100},"visible":true,"deviceNumber":"27601565","uid":"4973af_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Wohnzimmer Tür EG","deviceGroup":2,"did":9,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Wohnzimmer Tür EG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":100,"Position":0},"visible":true,"deviceNumber":"27601565","uid":"4971b0_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Wohnzimmer EG","deviceGroup":2,"did":10,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Wohnzimmer EG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":100,"Position":100},"visible":true,"deviceNumber":"27601565","uid":"49739c_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Küche EG","deviceGroup":2,"did":11,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Küche EG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":100,"Position":100},"visible":true,"deviceNumber":"27601565","uid":"4972f1_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Schlafzimmer Tür EG","deviceGroup":2,"did":12,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Schlafzimmer Tür EG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":0},"visible":true,"deviceNumber":"27601565","uid":"49739b_1","voiceControlledBy":"","origin":"HomePilot"},{"description":"Schlafzimmer EG","deviceGroup":2,"did":14,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset15"},"messages":[],"name":"Schlafzimmer EG","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Manuellbetrieb":0,"Position":100},"visible":true,"deviceNumber":"23602075","uid":"49a269_1","voiceControlledBy":"","origin":"HomePilot"},**### _{"description":"Treppenhaus","deviceGroup":2,"did":17,"hasErrors":0,"iconSetInverted":0,"iconSet":{"k":"iconset8"},"messages":[],"name":"Treppenhaus ","properties":{"closingContact":3,"dawn":3,"dusk":3,"motion":3,"rain":3,"smartphone":3,"smoke":3,"sun":3,"temperature":3,"time":3,"trigger":3,"warning":3,"wind":3},"statusValid":true,"statusesMap":{"Position":100},"visible":true,"deviceNumber":"10236020","uid":"49ff9d_1","voiceControlledBy":"","origin":"HomePilot"}]}_**

Es ist der untere Treppenhaus.

Gruß

Andreas

**Comment by homecineplexx** [comment]
Hallo
Bitte versuch die 0.0.45 Version und gib mir kurz bescheid

lg chris

Am Do., 16. Nov. 2023 um 21:11 Uhr schrieb AHahne64 <
***@***.***>:

**Comment by AHahne64** [comment]
Motor wird erkannt ist aber leider defekt. Ich werde ihn wahrscheinlich am Mittwoch auswechseln. Danach kann ich ihn dann auch testen. Einzige ist das er als m20 und nicht m10 erkannt wird.

Danke für die schnelle Hilfe.

**Comment by homecineplexx** [comment]
schönen guten morgen
Zuerst mal recht herzlichen DANK für deine Spende.

das mit dem kaputten motor tut mir leid. also ich hab wirklich schon sehr
sehr lange rademacher im einsatz und bis auf den eigentlichen homepilot war
nie etwas kaputt.
https://de.homepilot-smarthome.com/produkte/rollladen-sonnenschutz/rohrmotore/rollladenmotor-premium-smart-m20
wenn du dir den link anschaust und dazu deine
*"deviceNumber":"10236020" * entspricht
diese allerdings genau dem m20. darum hab ich das so eingebaut. sollte das
nicht so sein, glaub ich hat rademacher einen pallawatsch bei ihren nummern

glg chris

Am Mo., 20. Nov. 2023 um 20:56 Uhr schrieb AHahne64 <
***@***.***>:

**Comment by AHahne64** [comment]
Hallo Chris,

Motor läuft. Alles Super. Danke für die Tolle und schnelle Hilfe.
