### ISSUE TITLE
neues Heizkörperthermostat smart - keine Datenpunkte

### ISSUE THREAD

**Issue by jkret1966** [homecineplexx/ioBroker.homepilot20#64]
Hallo,
ich habe 10 neue DuoFern-Heizkörperthermostate smart (Rademacher/Homepilot) mit Bestellnummer 13601001 problemlos an der Rademacher SmartHome Zentrale angemeldet. Im IOB läuft der Adapter Homepilot20 mit Version 0.0.45 bisher problemlos mit 7 bereits vorhanden Geräten.
Im IO-Broker gibt es  7 Datenpunkte (5 Actuatoren und 2Sensoren) .
Die 10 neuen Geräte werden aber nicht automatisch in den Objekten als neue Datenpunkte angelegt.
In der Datei actuator-json sind alle neuen Geräte enthalten. Was muss ich tun, damit alle Datenpunkte angelegt werden?
Eine neue Instanz habe ich auch angelegt, da werden aber auch nur die "alten" Datenpunkte angelegt.

Auszug für ein neues Gerät in der Datei  actuator-json:
    {
      "description": "Ihre Gerätebeschreibung",
      "deviceGroup": 5,
      "did": 9,
      "hasErrors": 0,
      "iconSetInverted": 0,
      "iconSet": {
        "k": "iconset28"
      },
      "messages": [],
      "name": "Heizkörper WZ-Fenster",
      "properties": {
        "closingContact": 3,
        "dawn": 3,
        "dusk": 3,
        "motion": 3,
        "rain": 3,
        "smartphone": 3,
        "smoke": 3,
        "sun": 3,
        "temperature": 3,
        "time": 3,
        "trigger": 3,
        "warning": 3,
        "wind": 3
      },
      "statusValid": true,
      "statusesMap": {
        "Position": 210,
        "acttemperatur": 202
      },
      "visible": true,
      "deviceNumber": "13601001",
      "uid": "e1876a_1",
      "voiceControlledBy": "",
      "origin": "HomePilot",
      "batteryStatus": 100,
      "batteryLow": false,
      "posMin": 40,
      "posMax": 280
    },

**Comment by homecineplexx** [comment]
Hallo
Schau ich mir an

Glg Chris

jkret1966 ***@***.***> schrieb am So., 26. Nov. 2023, 11:02:

**Comment by homecineplexx** [comment]
Es gibt allerdings eine Beschreibung was alles integriert ist,wenn diese
Nummer deiner Geräte nicht aufscheint, kann das natürlich nicht
funktionieren

jkret1966 ***@***.***> schrieb am So., 26. Nov. 2023, 11:02:

**Comment by homecineplexx** [comment]
also, ich hab dir die 0.0.46er Version gebaut. Bitte probier es und gib mir
bescheid.
Solltest du zufrieden sein, bin ich auch immer gern offen und dankbar für
eine kleine Spende mittels dem Donate-Button unter
https://github.com/homecineplexx/ioBroker.homepilot20

Danke & viel Spaß damit
lg

Am So., 26. Nov. 2023 um 13:02 Uhr schrieb Christian Koller-Kink <
***@***.***>:

**Comment by jkret1966** [comment]
👍also das war ja mal ein schnelles Software-Update. Und es hat sofort funktioniert. 
Herzlichen Dank und noch einen schönen Sonntag.

**Comment by homecineplexx** [comment]
Danke für deine Spende.
Schnell..naja...ich hab meinen Adapter zum einen ganz gut unter Kontrolle
und auch gut aufgebaut.Da steckt eine Menge an Arbeit und Zeit drinnen

Schönen Sonntag


jkret1966 ***@***.***> schrieb am So., 26. Nov. 2023, 14:09:

**Comment by jkret1966** [comment]
Hallo Chris,,
ich habe das Protokoll auch als Text-Datei, ist besser lesbar ...
[Fehler Homepilot20 v0.0.46.txt](https://github.com/homecineplexx/ioBroker.homepilot20/files/13467711/Fehler.Homepilot20.v0.0.46.txt)

**Comment by homecineplexx** [comment]
Schau ich mir morgen in der früh gleich an

jkret1966 ***@***.***> schrieb am So., 26. Nov. 2023, 18:50:

**Comment by homecineplexx** [comment]
guten morgen
ich hab jetzt die 0.0.47 Version gebaut, da sollte das behoben.
Bitte probier diese Version aus

glg chris

Am So., 26. Nov. 2023 um 20:48 Uhr schrieb Christian Koller-Kink <
***@***.***>:

**Comment by jkret1966** [comment]
Guten Morgen,
0.0.47 funktioniert leider auch nicht , siehe auch Log im Anhang
[iobroker.2023-11-27.log.txt](https://github.com/homecineplexx/ioBroker.homepilot20/files/13471628/iobroker.2023-11-27.log.txt)

![image](https://github.com/homecineplexx/ioBroker.homepilot20/assets/57103858/6ea1b245-606c-4db9-b5c4-6969d583a68a)

**Comment by homecineplexx** [comment]
Hallo
ich hab mich natürlich gleich wieder dran gemacht und die 0.0.48 Version
gebaut.
Es ist immer ein bissl schwer etwas zu implementieren ohne testen zu
können. Bei mir läuft es ja meistens, weil ich die Geräte nicht habe.
Also bitte versuch es nochmals

lg

Am Mo., 27. Nov. 2023 um 09:32 Uhr schrieb jkret1966 <
***@***.***>:
