### ISSUE TITLE
Compatibility check mit js-controller 6.0.1

### ISSUE THREAD

**Issue by zaphod2** [homecineplexx/ioBroker.homepilot20#67]
Nach dem Update des js-controller auf 6.0.1 startet der Adapter nicht mehr und gibt die Fehlermeldungen aus.
Was muss ich tun um das wieder gerade zu Biegen?

![Screenshot 2024-06-11 121116](https://github.com/homecineplexx/ioBroker.homepilot20/assets/96678159/6c85b267-e1f3-45ac-a3b1-bfb4eb345c1b)

**Comment by homecineplexx** [comment]
Das weiß ich nicht und werd ich mir jetzt auch noch nicht anschauen, da der Js-Controller 6.0 erst Beta ist laut dem Beitrag https://forum.iobroker.net/topic/75206/beta-test-js-controller-kiera-v6-0

**Comment by zaphod2** [comment]
Danke, da war ich wieder zu schnell und habe mich nicht VORHER informiert.
Sicherung wieder zurück gespielt und es läuft wieder.

**Comment by homecineplexx** [comment]
super, freut mich!

**Comment by mcm1957** [comment]
@zaphod2 
Nö - du warts NICHT zu schnell. Der js-controller 6 ist im Bet-Test bei dem genau solche Fehler die im Adapter behoben werden müssen gefunden werden sollen. DANKE dass du diesen Issue erstellt hast.

@homecineplexx 
Bitte aktualisisere deinen Adapter. Der obige Fehler wird dadurch ausgelöst dass dieser Adapter 
- veraltete dependencies, insbesondere eine veraltete dependency zu adapter-cor aufweist
- der Adapetr die standardmäßigen Githuib Tests nicht verwende wodurch dieser Fehler nicht schon früher aufgefallen ist.

Es ist jedenfalls NICHT sinnvoll mit einer Fehlerrbehebung auf stable des js-controllers zu warten, da kein Fehler des js-controllers vorliegt

**Comment by meicker** [comment]
Js-controller ist jetzt stable und es funktioniert leider noch immer nicht. Hab ich was verpasst oder wurde noch nichts angepasst ?

**Comment by zaphod2** [comment]
Also bei mir funktioniert es seid v 0.0.53 wieder  zuverlässig.

**Comment by mcm1957** [comment]
Und wenn was nicht funktioniert ist es nur bedingt sinnvoll ein GECLOSTES Issue zu befüllen :-)

**Comment by meicker** [comment]
Anstatt nutzloser Kommentare wäre ggf. ein Hinweis gut gewesen was ich verpasst habe - das hat aber schon jemand anders erledigt. Vielen Dank für die konstruktiven Hinweise ! :-)

**Comment by mcm1957** [comment]
> Anstatt nutzloser Kommentare wäre ggf. ein Hinweis gut gewesen was ich verpasst habe - das hat aber schon jemand anders erledigt. Vielen Dank für die konstruktiven Hinweise ! :-)

**Was du verpasst hast?**
Du benutzt einen Adapter den du von Github installierst, Davon wird explizit abgeraten - insbesondere wenn du weder in direktem Kontakt mit dem Dev stehst noch dir bewusst bist dass due bei von GitHub installierten Adapter primär auf dich alleine gestellt bist.

Also nochmals - damit du das nächste Mal besser informiert bist:

**Von direkten Installation von GitHub - insbesondere auf produktiven Systemen - wird explizit abgeraten.** GitHub Versionen können sich jederzeit (auch kurzfristig) ändern und durchaus auch in sich inkonsistent und fehlerhaft sein. Versionsangaben von GitHub Installationen sind Schall und Rauch da die Versionsnummer zumindest bei Verwendung der standardmäßigen Umgebung erst im Zuge der Releaseerstellung geändert wird.

Auf explizite Aufforderung durch den Entwickler kann eine GitHub Installation zur Fehlereingrenzung oder zum Test neuer Funktionalität - unter Inkaufnahme des erhöhten Risikos - natürlich erfolgen.

Adapter die nur via GitHub installierbar sind sind mit erhöhter Vorsicht zu betrachten. Hier sollte der Entwickler drum ersucht werden eine Aufnahme in die Repositories zu veranlassen indem z.B. ein Issue im Adapterrepository erstellt wird.

**Comment by meicker** [comment]
Dankeschön - das war ausführlich und damit hätte ich was anfangen können. Wie gesagt, der Tip kam schon in einem andren Issue mit dem gleichen Thema. Hab ihn über NPM installiert. Läuft alles. Viele Grüsse,MarcAm 03.08.2024 um 23:38 schrieb Martin M. ***@***.***>:﻿

Anstatt nutzloser Kommentare wäre ggf. ein Hinweis gut gewesen was ich verpasst habe - das hat aber schon jemand anders erledigt. Vielen Dank für die konstruktiven Hinweise ! :-)

Was du verpasst hast?
Du benutzt einen Adapter den du von Github installierst, Davon wird explizit abgeraten - insbesondere wenn du weder in direktem Kontakt mit dem Dev stehst noch dir bewusst bist dass due bei von GitHub installierten Adapter primär auf dich alleine gestellt bist.
Also nochmals - damit du das nächste Mal besser informiert bist:
Von direkten Installation von GitHub - insbesondere auf produktiven Systemen - wird explizit abgeraten. GitHub Versionen können sich jederzeit (auch kurzfristig) ändern und durchaus auch in sich inkonsistent und fehlerhaft sein. Versionsangaben von GitHub Installationen sind Schall und Rauch da die Versionsnummer zumindest bei Verwendung der standardmäßigen Umgebung erst im Zuge der Releaseerstellung geändert wird.
Auf explizite Aufforderung durch den Entwickler kann eine GitHub Installation zur Fehlereingrenzung oder zum Test neuer Funktionalität - unter Inkaufnahme des erhöhten Risikos - natürlich erfolgen.
Adapter die nur via GitHub installierbar sind sind mit erhöhter Vorsicht zu betrachten. Hier sollte der Entwickler drum ersucht werden eine Aufnahme in die Repositories zu veranlassen indem z.B. ein Issue im Adapterrepository erstellt wird.
