### ISSUE TITLE
Adapter seems to be incompatible with JS-Controller 6.x

### ISSUE THREAD

**Issue by Wildbill-Z** [homecineplexx/ioBroker.homepilot20#69]
As seen [here](https://forum.iobroker.net/post/1169824) in iobroker forum, this adapter seems to have problems with JS-Controler 6.x.

**Comment by mcm1957** [comment]
@mcm1957
just as reminder

**Comment by homecineplexx** [comment]
thanks for this information but as i wrote in this ticket https://github.com/homecineplexx/ioBroker.homepilot20/issues/67
as i remember the js-controller is in beta status or? so i wait for a stable version

**Comment by mcm1957** [comment]
Please do NOT wait.  Time for adapter adaptions is now. The beta test phase is the time to fix incompatibilities and this is done by all active developers. Otherweise users will be frustrated when updateing js-controller  and an outdated adapter does not work.

Is there any special reason to wait ?

If the adapter is known not to work with js-controller 6 at time of stable release it must be liste ats deprectaed / outdated at js-controller release notes.

**Comment by meicker** [comment]
Js-controller ist jetzt stable und es funktioniert leider noch immer nicht. Hab ich was verpasst oder wurde noch nichts angepasst ?

**Comment by Wildbill-Z** [comment]
@meicker Wenn Du in den Changelog schaust, siehst Du, dass am 16.06. mit 0.0.53 eine Version erstellt wurde, die Kompatibilität mit 6.x bringt. Da der Adapter aber noch in keinem Repo (stable oder beta) ist, musst Du in iobroker den Expertenmodus einschalten, anschließend oben auf die Katze und aus NPM installieren. Dann kommt die 0.0.58. Anschließend Expertenmodus gleich wieder ausschalten. Und bitte NICHT von Github installieren, sondern über den Reiter NPM bei der Katze.

Gruss, Jürgen


<img width="1180" alt="image" src="https://github.com/user-attachments/assets/b5027845-6184-4f45-8568-cb3d8257c6eb">

**Comment by meicker** [comment]
Hi Jürgen,vielen Dank ! Mache ich gleich. 😊Viele Grüsse,MarcAm 03.08.2024 um 20:00 schrieb Wildbill-Z ***@***.***>:﻿
@meicker Wenn Du in den Changelog schaust, siehst Du, dass am 16.06. mit 0.0.53 eine Version erstellt wurde, die Kompatibilität mit 6.x bringt. Da der Adapter aber noch in keinem Repo (stable oder beta) ist, musst Du in iobroker den Expertenmodus einschalten, anschließend oben auf die Katze und aus NPM installieren. Dann kommt die 0.0.58. Anschließend Expertenmodus gleich wieder ausschalten. Und bitte NICHT von Github installieren, sondern über den Reiter NPM bei der Katze.
Gruss, Jürgen
image.png (view on web)

**Comment by Wildbill-Z** [comment]
Da das Problem mit fehlender Kompatibilität mit 6.x augenscheinlich behoben ist, mache ich das Issue mal zu. Wenn es doch noch Probleme gibt, hier weiterschreiben oder neues Issue.

**Comment by mcm1957** [comment]
Da dieser Adapter bisher NICHT in die offiziellen Repositories aufgenommen wurde der Vollständigkeit und als Info - NICHT als Kritik:

Von direkten Installation von GitHub - insbesondere auf produktiven Systemen - wird explizit abgeraten. GitHub Versionen können sich jederzeit (auch kurzfristig) ändern und durchaus auch in sich inkonsistent und fehlerhaft sein. Versionsangaben von GitHub Installationen sind Schall und Rauch da die Versionsnummer zumindest bei Verwendung der standardmäßigen Umgebung erst im Zuge der Releaseerstellung geändert wird.

Auf explizite Aufforderung durch den Entwickler kann eine GitHub Installation zur Fehlereingrenzung oder zum Test neuer Funktionalität - unter Inkaufnahme des erhöhten Risikos - natürlich erfolgen.

Adapter die nur via GitHub installierbar sind sind mit erhöhter Vorsicht zu betrachten. Hier sollte der Entwickler drum ersucht werden eine Aufnahme in die Repositories zu veranlassen indem z.B. ein Issue im Adapterrepository erstellt wird.
