### ISSUE TITLE
Error: Invalid device confirm

### ISSUE THREAD

**Issue by Day1983** [homecineplexx/ioBroker.homepilot20#72]
Im LOG taucht diese Meldung auf.

Adapter 0.60.
Node 20.16.
npm  10.8.1
admin  7.0.22

![image](https://github.com/user-attachments/assets/102e6fb3-9574-447f-874e-91202c586461)

**Comment by homecineplexx** [comment]
Please Show your settings and which Homepilot gateway you use

**Comment by Day1983** [comment]
Die Settings:
![image](https://github.com/user-attachments/assets/b6307398-46e5-41fe-baf5-472501071732)

Die Bridge ist die von Rademacher HomePilet 2 (schwarze Kiste :-)  ) mit der duefern, die Firmware ist aktuell auf die 5.7.15

**Comment by homecineplexx** [comment]
Wenn's die Bridge ist, was hältst du davon, wenn du in den instanz-settings auch Bridge ankreuzt?

**Comment by homecineplexx** [comment]
Außerdem, jetzt schnall ich es erst!

Was genau soll ich im Homepilot Adapter mit einer TAPO Meldung??
Falsches GIT bzw falscher Adapter
