### ISSUE TITLE
Cannot connect to Homepilot: Error: connect ENETUNREACH

### ISSUE THREAD

**Issue by Bibo13** [homecineplexx/ioBroker.homepilot20#8]
Seit dem Update auf Admin Version 3.6.10 habe ich andauernd diese Fehlemeldungen.

homepilot20.0 | 2019-11-08 15:13:16.876 | warn | Scenes -> Cannot connect to Homepilot: Error: connect ENETUNREACH 192.168.2.46:80 - Local (0.0.0.0:0)
-- | -- | -- | --
homepilot20.0 | 2019-11-08 15:13:16.872 | warn | Read actuator -> Cannot connect to Homepilot: Error: connect ENETUNREACH 192.168.2.46:80 - Local (0.0.0.0:0)
homepilot20.0 | 2019-11-08 15:13:16.771 | warn | Transmitter sensors -> Cannot connect to Homepilot: Error: connect ENETUNREACH 192.168.2.46:80 - Local (0.0.0.0:0)
homepilot20.0 | 2019-11-08 15:13:16.771 | warn | Read sensors -> Cannot connect to Homepilot: Error: connect ENETUNREACH 192.168.2.46:80 - Local (0.0.0.0:0)

was kann ich tun?

**Comment by homecineplexx** [comment]
ja das hat aber meines Erachtens weder was mit dem Admin noch dem Homepilot20 Adapter zu tun.
Da solltest eher mal dein Netzwerk checken, bzw den Rademacher Homepilot 2. Der ist scheinbar nicht immer erreichbar!
