### ISSUE TITLE
Logeinträge WARNING Unknown Actuator

### ISSUE THREAD

**Issue by meicker** [homecineplexx/ioBroker.homepilot20#9]
Im  Log erscheinen seit einiger Zeit folgende Einträge:

homepilot20.0 | 2019-12-21 19:40:36.561 | warn | (23877) Unknown Actuator deviceNumber=99999983
-- | -- | -- | --
homepilot20.0 | 2019-12-21 19:40:36.559 | warn | (23877) Unknown Actuator deviceNumber=99999980

Sie erscheinen sehr häufig und unter Actuator kann ich weder Nummer xxx83 noch xxx80 finden.

Hat das evtl mit dem Rademacher Update für HUE zu tun ?

**Comment by funky4t** [comment]
Hi,
erstmal super vielen Dank für den Adapter ich hab folgende Logs mit Warning und folgende Infos dazu:

<img width="564" alt="Log" src="https://user-images.githubusercontent.com/57875762/71549641-0a82e980-29c1-11ea-9d30-f7ad78e8bd49.png">

Die ID 32004219 ist meine Innenkamera von Rademacher. Darin ist ein PIR Sensor integriert, der scheinbar im Adapter nicht so will. Das hatte ich auch schon VOR dem Hue Update des Homepilots. Kann man recht gut hier sehen:

<img width="1287" alt="Cam" src="https://user-images.githubusercontent.com/57875762/71549706-36eb3580-29c2-11ea-801e-9a54584b2a1f.png">

 Die deviceNumber=99999980 und deviceNumber=99999983 hatte ich bei mir in den Instanzen als iOS Geräte für die Geopilot App sprich als GPS Sensor. Ich hab da im HP2 keinen sauberen Sync hinbekommen und als sich diese beiden Warnmeldungen einstellten (am Anfang hatte ich die nicht!) hab ich die Instanzen aus dem iObroker geworfen. Leider blieben die Warnings. Hab die "Geräte" dann auch im HP2 abgemeldet...ebenfalls keine Änderung im iObroker. Ich bin mir zu 99,9% sicher, dass die IDs 80 und 83 zu meinen beiden iOS Geräten gehörten und nicht zu den Hues. Davon hab ich 3 im Hause, da wäre die Zahl der IDs mit 2 ja auch zu wenig, zudem sind die im HP Adapter bei mir auch nicht aufgeführt.

@meicker: Hast du die Geopilot App in der Benutzung? Unter Umständen mal genutzt aber nicht mehr aktiv? Ich weiß, dass die Jungs von Rademacher da nen Problem mit der iOS Version haben, deswegen hab ich sie auch wieder runtergeworfen....

**Comment by meicker** [comment]
Hi !
die Geopilot App habe ich aktuell noch installiert und sie funktioniert auch -jetzt- 
Zuvor hatte ich mehrere Fehlversuche und habe auch Kopplungen wieder gelöscht bzw. abgemeldet. 

Aktuell sind aber wie bei Dir auch die Geräte HUE Leuchten. Die 80 ist die Bridge jnd die 83 ist mehrfach an Leuchten Vergeben. 

Viele Grüsse,
Marc

**Comment by homecineplexx** [comment]
Hallo  Meicker

ich hab dir das auch schon im Forum geschrieben.
ich bräuchte folgende JSON Daten von dir: http://<homepilot-ip>/v4/devices?devtype=Actuator
dann kann ich mir das ansehen und eventuell einbauen.

**Comment by homecineplexx** [comment]
hallo funky4t
ich bräuchte von dir folgende jSON Daten: 
  -) http:///v4/devices?devtype=Actuator
  -) http:///v4/devices?devtype=Sensor

Lg

**Comment by homecineplexx** [comment]
funky4t 
sorry, jetzt stimmen die Links. du mußt nur homepilot-ip mit der ip von deinem homepilot ersetzen

**Comment by funky4t** [comment]
Check, jetzt hab ich unterschiedliche Infos ziehen können. Daten hast du per eMail erhalten.
ich danke schon jetzt vielmals! :)

**Comment by homecineplexx** [comment]
super danke, ich schau mir das mal an

**Comment by homecineplexx** [comment]
see new log
